
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 748_2_DIAL

#ifndef _FACE_748_2_DIAL_H
#define _FACE_748_2_DIAL_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

    extern lv_obj_t *face_748_2_dial;
	extern lv_obj_t *face_748_2_dial_0_424;
	extern lv_obj_t *face_748_2_dial_1_65535;
	extern lv_obj_t *face_748_2_dial_3_101560;
	extern lv_obj_t *face_748_2_dial_5_72552;
	extern lv_obj_t *face_748_2_dial_6_58522;
	extern lv_obj_t *face_748_2_dial_7_58522;
	extern lv_obj_t *face_748_2_dial_8_58522;
	extern lv_obj_t *face_748_2_dial_9_58522;
	extern lv_obj_t *face_748_2_dial_10_58522;
	extern lv_obj_t *face_748_2_dial_11_58522;
	extern lv_obj_t *face_748_2_dial_12_58522;
	extern lv_obj_t *face_748_2_dial_13_58522;
	extern lv_obj_t *face_748_2_dial_14_80686;
	extern lv_obj_t *face_748_2_dial_15_82792;
	extern lv_obj_t *face_748_2_dial_16_82792;
	extern lv_obj_t *face_748_2_dial_17_82792;
	extern lv_obj_t *face_748_2_dial_18_82792;
	extern lv_obj_t *face_748_2_dial_19_80958;
	extern lv_obj_t *face_748_2_dial_20_80958;


	LV_IMG_DECLARE(face_748_2_dial_dial_img_0_424_0);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_1_65535_0);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_2_94526_0);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_2_94526_1);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_2_94526_2);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_2_94526_3);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_2_94526_4);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_2_94526_5);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_2_94526_6);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_3_101560_0);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_3_101560_1);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_3_101560_2);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_3_101560_3);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_3_101560_4);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_3_101560_5);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_3_101560_6);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_0);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_1);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_2);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_3);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_4);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_5);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_6);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_7);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_8);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_9);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_10);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_4_60206_11);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_0);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_1);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_2);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_3);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_4);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_5);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_6);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_7);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_8);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_9);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_10);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_5_72552_11);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_6_58522_0);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_6_58522_1);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_6_58522_2);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_6_58522_3);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_6_58522_4);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_6_58522_5);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_6_58522_6);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_6_58522_7);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_6_58522_8);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_6_58522_9);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_14_80686_0);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_15_82792_0);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_15_82792_1);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_15_82792_2);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_15_82792_3);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_15_82792_4);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_15_82792_5);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_15_82792_6);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_15_82792_7);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_15_82792_8);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_15_82792_9);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_19_80958_0);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_19_80958_1);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_19_80958_2);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_19_80958_3);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_19_80958_4);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_19_80958_5);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_19_80958_6);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_19_80958_7);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_19_80958_8);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_19_80958_9);
	LV_IMG_DECLARE(face_748_2_dial_dial_img_preview_0);


    void onFaceEvent(lv_event_t * e);

    void init_face_748_2_dial(void);
    void update_time_748_2_dial(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_748_2_dial(int temp, int icon);
    void update_status_748_2_dial(int battery, bool connection);
    void update_activity_748_2_dial(int steps, int distance, int kcal);
    void update_health_748_2_dial(int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
