
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 748_2_DIAL

#include "748_2_dial.h"

lv_obj_t *face_748_2_dial;
lv_obj_t *face_748_2_dial_0_424;
lv_obj_t *face_748_2_dial_1_65535;
lv_obj_t *face_748_2_dial_3_101560;
lv_obj_t *face_748_2_dial_5_72552;
lv_obj_t *face_748_2_dial_6_58522;
lv_obj_t *face_748_2_dial_7_58522;
lv_obj_t *face_748_2_dial_8_58522;
lv_obj_t *face_748_2_dial_9_58522;
lv_obj_t *face_748_2_dial_10_58522;
lv_obj_t *face_748_2_dial_11_58522;
lv_obj_t *face_748_2_dial_12_58522;
lv_obj_t *face_748_2_dial_13_58522;
lv_obj_t *face_748_2_dial_14_80686;
lv_obj_t *face_748_2_dial_15_82792;
lv_obj_t *face_748_2_dial_16_82792;
lv_obj_t *face_748_2_dial_17_82792;
lv_obj_t *face_748_2_dial_18_82792;
lv_obj_t *face_748_2_dial_19_80958;
lv_obj_t *face_748_2_dial_20_80958;


/*
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif
*/

const lv_img_dsc_t *face_748_2_dial_dial_img_2_94526_group[] = {
	&face_748_2_dial_dial_img_2_94526_0,
	&face_748_2_dial_dial_img_2_94526_1,
	&face_748_2_dial_dial_img_2_94526_2,
	&face_748_2_dial_dial_img_2_94526_3,
	&face_748_2_dial_dial_img_2_94526_4,
	&face_748_2_dial_dial_img_2_94526_5,
	&face_748_2_dial_dial_img_2_94526_6,
};
const lv_img_dsc_t *face_748_2_dial_dial_img_3_101560_group[] = {
	&face_748_2_dial_dial_img_3_101560_0,
	&face_748_2_dial_dial_img_3_101560_1,
	&face_748_2_dial_dial_img_3_101560_2,
	&face_748_2_dial_dial_img_3_101560_3,
	&face_748_2_dial_dial_img_3_101560_4,
	&face_748_2_dial_dial_img_3_101560_5,
	&face_748_2_dial_dial_img_3_101560_6,
};
const lv_img_dsc_t *face_748_2_dial_dial_img_4_60206_group[] = {
	&face_748_2_dial_dial_img_4_60206_0,
	&face_748_2_dial_dial_img_4_60206_1,
	&face_748_2_dial_dial_img_4_60206_2,
	&face_748_2_dial_dial_img_4_60206_3,
	&face_748_2_dial_dial_img_4_60206_4,
	&face_748_2_dial_dial_img_4_60206_5,
	&face_748_2_dial_dial_img_4_60206_6,
	&face_748_2_dial_dial_img_4_60206_7,
	&face_748_2_dial_dial_img_4_60206_8,
	&face_748_2_dial_dial_img_4_60206_9,
	&face_748_2_dial_dial_img_4_60206_10,
	&face_748_2_dial_dial_img_4_60206_11,
};
const lv_img_dsc_t *face_748_2_dial_dial_img_5_72552_group[] = {
	&face_748_2_dial_dial_img_5_72552_0,
	&face_748_2_dial_dial_img_5_72552_1,
	&face_748_2_dial_dial_img_5_72552_2,
	&face_748_2_dial_dial_img_5_72552_3,
	&face_748_2_dial_dial_img_5_72552_4,
	&face_748_2_dial_dial_img_5_72552_5,
	&face_748_2_dial_dial_img_5_72552_6,
	&face_748_2_dial_dial_img_5_72552_7,
	&face_748_2_dial_dial_img_5_72552_8,
	&face_748_2_dial_dial_img_5_72552_9,
	&face_748_2_dial_dial_img_5_72552_10,
	&face_748_2_dial_dial_img_5_72552_11,
};
const lv_img_dsc_t *face_748_2_dial_dial_img_6_58522_group[] = {
	&face_748_2_dial_dial_img_6_58522_0,
	&face_748_2_dial_dial_img_6_58522_1,
	&face_748_2_dial_dial_img_6_58522_2,
	&face_748_2_dial_dial_img_6_58522_3,
	&face_748_2_dial_dial_img_6_58522_4,
	&face_748_2_dial_dial_img_6_58522_5,
	&face_748_2_dial_dial_img_6_58522_6,
	&face_748_2_dial_dial_img_6_58522_7,
	&face_748_2_dial_dial_img_6_58522_8,
	&face_748_2_dial_dial_img_6_58522_9,
};
const lv_img_dsc_t *face_748_2_dial_dial_img_15_82792_group[] = {
	&face_748_2_dial_dial_img_15_82792_0,
	&face_748_2_dial_dial_img_15_82792_1,
	&face_748_2_dial_dial_img_15_82792_2,
	&face_748_2_dial_dial_img_15_82792_3,
	&face_748_2_dial_dial_img_15_82792_4,
	&face_748_2_dial_dial_img_15_82792_5,
	&face_748_2_dial_dial_img_15_82792_6,
	&face_748_2_dial_dial_img_15_82792_7,
	&face_748_2_dial_dial_img_15_82792_8,
	&face_748_2_dial_dial_img_15_82792_9,
};
const lv_img_dsc_t *face_748_2_dial_dial_img_19_80958_group[] = {
	&face_748_2_dial_dial_img_19_80958_0,
	&face_748_2_dial_dial_img_19_80958_1,
	&face_748_2_dial_dial_img_19_80958_2,
	&face_748_2_dial_dial_img_19_80958_3,
	&face_748_2_dial_dial_img_19_80958_4,
	&face_748_2_dial_dial_img_19_80958_5,
	&face_748_2_dial_dial_img_19_80958_6,
	&face_748_2_dial_dial_img_19_80958_7,
	&face_748_2_dial_dial_img_19_80958_8,
	&face_748_2_dial_dial_img_19_80958_9,
};


void init_face_748_2_dial(void){
    face_748_2_dial = lv_obj_create(lv_scr_act());
    lv_obj_set_size(face_748_2_dial, 240, 240);
    lv_obj_clear_flag(face_748_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_748_2_dial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_748_2_dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_748_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_748_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_748_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_748_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_748_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    //lv_obj_add_event_cb(face_748_2_dial, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_748_2_dial_0_424 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_0_424, &face_748_2_dial_dial_img_0_424_0);
    lv_obj_set_width(face_748_2_dial_0_424, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_0_424, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_0_424, 0);
    lv_obj_set_y(face_748_2_dial_0_424, 0);
    lv_obj_add_flag(face_748_2_dial_0_424, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_0_424, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_1_65535 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_1_65535, &face_748_2_dial_dial_img_1_65535_0);
    lv_obj_set_width(face_748_2_dial_1_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_1_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_1_65535, 177);
    lv_obj_set_y(face_748_2_dial_1_65535, 91);
    lv_obj_add_flag(face_748_2_dial_1_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_1_65535, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_3_101560 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_3_101560, &face_748_2_dial_dial_img_3_101560_0);
    lv_obj_set_width(face_748_2_dial_3_101560, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_3_101560, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_3_101560, 116);
    lv_obj_set_y(face_748_2_dial_3_101560, 157);
    lv_obj_add_flag(face_748_2_dial_3_101560, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_3_101560, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_5_72552 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_5_72552, &face_748_2_dial_dial_img_5_72552_0);
    lv_obj_set_width(face_748_2_dial_5_72552, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_5_72552, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_5_72552, 130);
    lv_obj_set_y(face_748_2_dial_5_72552, 82);
    lv_obj_add_flag(face_748_2_dial_5_72552, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_5_72552, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_6_58522 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_6_58522, &face_748_2_dial_dial_img_6_58522_0);
    lv_obj_set_width(face_748_2_dial_6_58522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_6_58522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_6_58522, 153);
    lv_obj_set_y(face_748_2_dial_6_58522, 40);
    lv_obj_add_flag(face_748_2_dial_6_58522, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_6_58522, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_7_58522 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_7_58522, &face_748_2_dial_dial_img_6_58522_0);
    lv_obj_set_width(face_748_2_dial_7_58522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_7_58522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_7_58522, 142);
    lv_obj_set_y(face_748_2_dial_7_58522, 40);
    lv_obj_add_flag(face_748_2_dial_7_58522, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_7_58522, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_8_58522 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_8_58522, &face_748_2_dial_dial_img_6_58522_0);
    lv_obj_set_width(face_748_2_dial_8_58522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_8_58522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_8_58522, 131);
    lv_obj_set_y(face_748_2_dial_8_58522, 40);
    lv_obj_add_flag(face_748_2_dial_8_58522, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_8_58522, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_9_58522 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_9_58522, &face_748_2_dial_dial_img_6_58522_0);
    lv_obj_set_width(face_748_2_dial_9_58522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_9_58522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_9_58522, 170);
    lv_obj_set_y(face_748_2_dial_9_58522, 191);
    lv_obj_add_flag(face_748_2_dial_9_58522, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_9_58522, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_10_58522 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_10_58522, &face_748_2_dial_dial_img_6_58522_0);
    lv_obj_set_width(face_748_2_dial_10_58522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_10_58522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_10_58522, 159);
    lv_obj_set_y(face_748_2_dial_10_58522, 191);
    lv_obj_add_flag(face_748_2_dial_10_58522, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_10_58522, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_11_58522 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_11_58522, &face_748_2_dial_dial_img_6_58522_0);
    lv_obj_set_width(face_748_2_dial_11_58522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_11_58522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_11_58522, 148);
    lv_obj_set_y(face_748_2_dial_11_58522, 191);
    lv_obj_add_flag(face_748_2_dial_11_58522, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_11_58522, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_12_58522 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_12_58522, &face_748_2_dial_dial_img_6_58522_0);
    lv_obj_set_width(face_748_2_dial_12_58522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_12_58522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_12_58522, 137);
    lv_obj_set_y(face_748_2_dial_12_58522, 191);
    lv_obj_add_flag(face_748_2_dial_12_58522, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_12_58522, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_13_58522 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_13_58522, &face_748_2_dial_dial_img_6_58522_0);
    lv_obj_set_width(face_748_2_dial_13_58522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_13_58522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_13_58522, 126);
    lv_obj_set_y(face_748_2_dial_13_58522, 191);
    lv_obj_add_flag(face_748_2_dial_13_58522, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_13_58522, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_14_80686 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_14_80686, &face_748_2_dial_dial_img_14_80686_0);
    lv_obj_set_width(face_748_2_dial_14_80686, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_14_80686, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_14_80686, 166);
    lv_obj_set_y(face_748_2_dial_14_80686, 117);
    lv_obj_add_flag(face_748_2_dial_14_80686, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_14_80686, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_15_82792 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_15_82792, &face_748_2_dial_dial_img_15_82792_0);
    lv_obj_set_width(face_748_2_dial_15_82792, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_15_82792, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_15_82792, 138);
    lv_obj_set_y(face_748_2_dial_15_82792, 102);
    lv_obj_add_flag(face_748_2_dial_15_82792, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_15_82792, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_16_82792 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_16_82792, &face_748_2_dial_dial_img_15_82792_0);
    lv_obj_set_width(face_748_2_dial_16_82792, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_16_82792, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_16_82792, 110);
    lv_obj_set_y(face_748_2_dial_16_82792, 102);
    lv_obj_add_flag(face_748_2_dial_16_82792, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_16_82792, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_17_82792 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_17_82792, &face_748_2_dial_dial_img_15_82792_0);
    lv_obj_set_width(face_748_2_dial_17_82792, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_17_82792, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_17_82792, 204);
    lv_obj_set_y(face_748_2_dial_17_82792, 102);
    lv_obj_add_flag(face_748_2_dial_17_82792, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_17_82792, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_18_82792 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_18_82792, &face_748_2_dial_dial_img_15_82792_0);
    lv_obj_set_width(face_748_2_dial_18_82792, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_18_82792, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_18_82792, 176);
    lv_obj_set_y(face_748_2_dial_18_82792, 102);
    lv_obj_add_flag(face_748_2_dial_18_82792, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_18_82792, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_19_80958 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_19_80958, &face_748_2_dial_dial_img_19_80958_0);
    lv_obj_set_width(face_748_2_dial_19_80958, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_19_80958, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_19_80958, 199);
    lv_obj_set_y(face_748_2_dial_19_80958, 82);
    lv_obj_add_flag(face_748_2_dial_19_80958, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_19_80958, LV_OBJ_FLAG_SCROLLABLE );

    face_748_2_dial_20_80958 = lv_img_create(face_748_2_dial);
    lv_img_set_src(face_748_2_dial_20_80958, &face_748_2_dial_dial_img_19_80958_0);
    lv_obj_set_width(face_748_2_dial_20_80958, LV_SIZE_CONTENT);
    lv_obj_set_height(face_748_2_dial_20_80958, LV_SIZE_CONTENT);
    lv_obj_set_x(face_748_2_dial_20_80958, 189);
    lv_obj_set_y(face_748_2_dial_20_80958, 82);
    lv_obj_add_flag(face_748_2_dial_20_80958, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_748_2_dial_20_80958, LV_OBJ_FLAG_SCROLLABLE );

}

void update_time_748_2_dial(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
	lv_img_set_src(face_748_2_dial_3_101560, face_748_2_dial_dial_img_3_101560_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_748_2_dial_5_72552, face_748_2_dial_dial_img_5_72552_group[(month / 1) % 12]);
	lv_img_set_src(face_748_2_dial_15_82792, face_748_2_dial_dial_img_15_82792_group[(hour / 1) % 10]);
	lv_img_set_src(face_748_2_dial_16_82792, face_748_2_dial_dial_img_15_82792_group[(hour / 10) % 10]);
	lv_img_set_src(face_748_2_dial_17_82792, face_748_2_dial_dial_img_15_82792_group[(minute / 1) % 10]);
	lv_img_set_src(face_748_2_dial_18_82792, face_748_2_dial_dial_img_15_82792_group[(minute / 10) % 10]);
	lv_img_set_src(face_748_2_dial_19_80958, face_748_2_dial_dial_img_19_80958_group[(day / 1) % 10]);
	lv_img_set_src(face_748_2_dial_20_80958, face_748_2_dial_dial_img_19_80958_group[(day / 10) % 10]);

}

void update_weather_748_2_dial(int temp, int icon)
{

}

void update_status_748_2_dial(int battery, bool connection){

}

void update_activity_748_2_dial(int steps, int distance, int kcal)
{
	lv_img_set_src(face_748_2_dial_9_58522, face_748_2_dial_dial_img_6_58522_group[(steps / 1) % 10]);
	lv_img_set_src(face_748_2_dial_10_58522, face_748_2_dial_dial_img_6_58522_group[(steps / 10) % 10]);
	lv_img_set_src(face_748_2_dial_11_58522, face_748_2_dial_dial_img_6_58522_group[(steps / 100) % 10]);
	lv_img_set_src(face_748_2_dial_12_58522, face_748_2_dial_dial_img_6_58522_group[(steps / 1000) % 10]);
	lv_img_set_src(face_748_2_dial_13_58522, face_748_2_dial_dial_img_6_58522_group[(steps / 10000) % 10]);

}

void update_health_748_2_dial(int bpm, int oxygen)
{
	lv_img_set_src(face_748_2_dial_6_58522, face_748_2_dial_dial_img_6_58522_group[(bpm / 1) % 10]);
	lv_img_set_src(face_748_2_dial_7_58522, face_748_2_dial_dial_img_6_58522_group[(bpm / 10) % 10]);
	lv_img_set_src(face_748_2_dial_8_58522, face_748_2_dial_dial_img_6_58522_group[(bpm / 100) % 10]);

}

