
// File generated by bin2lvgl
// developed by fbiego.
// https://github.com/fbiego
// modified by Daniel Kampert.
// https://github.com/kampi
// Watchface: goog

#include <lvgl.h>

#include <zephyr/logging/log.h>

#include "ui/zsw_ui.h"
#include "applications/watchface/watchface_app.h"

LOG_MODULE_REGISTER(watchface_goog, LOG_LEVEL_WRN);

static lv_obj_t *face_goog;
static lv_obj_t *face_goog = NULL;
static watchface_app_evt_listener ui_goog_evt_cb;

static int last_date = -1;
static int last_day = -1;
static int last_month = -1;
static int last_year = -1;
static int last_weekday = -1;
static int last_hour = -1;
static int last_minute = -1;

static int last_steps = -1;
static int last_distance = -1;
static int last_kcal = -1;

static lv_obj_t *face_goog_0_1004;
static lv_obj_t *face_goog_1_59114;
static lv_obj_t *face_goog_2_59114;
static lv_obj_t *face_goog_3_59114;
static lv_obj_t *face_goog_4_59114;
static lv_obj_t *face_goog_5_59114;
static lv_obj_t *face_goog_6_59114;
static lv_obj_t *face_goog_7_59114;
static lv_obj_t *face_goog_8_59114;
static lv_obj_t *face_goog_9_59114;
static lv_obj_t *face_goog_12_60913;
static lv_obj_t *face_goog_13_59114;
static lv_obj_t *face_goog_14_59114;
static lv_obj_t *face_goog_15_59114;
static lv_obj_t *face_goog_16_59114;
static lv_obj_t *face_goog_17_59114;
static lv_obj_t *face_goog_18_59114;
static lv_obj_t *face_goog_19_61460;
static lv_obj_t *face_goog_20_61728;
static lv_obj_t *face_goog_22_72744;
static lv_obj_t *face_goog_23_59114;
static lv_obj_t *face_goog_24_59114;
static lv_obj_t *face_goog_27_87610;
static lv_obj_t *face_goog_28_97966;
static lv_obj_t *face_goog_29_97966;
static lv_obj_t *face_goog_30_97966;
static lv_obj_t *face_goog_31_97966;
static lv_obj_t *face_goog_34_59114;
static lv_obj_t *face_goog_35_59114;
static lv_obj_t *face_goog_36_130812;
static lv_obj_t *face_goog_37_65535;
static lv_obj_t *face_goog_41_130994;

ZSW_LV_IMG_DECLARE(face_goog_0_1004_0);
ZSW_LV_IMG_DECLARE(face_goog_1_59114_0);
ZSW_LV_IMG_DECLARE(face_goog_1_59114_1);
ZSW_LV_IMG_DECLARE(face_goog_1_59114_2);
ZSW_LV_IMG_DECLARE(face_goog_1_59114_3);
ZSW_LV_IMG_DECLARE(face_goog_1_59114_4);
ZSW_LV_IMG_DECLARE(face_goog_1_59114_5);
ZSW_LV_IMG_DECLARE(face_goog_1_59114_6);
ZSW_LV_IMG_DECLARE(face_goog_1_59114_7);
ZSW_LV_IMG_DECLARE(face_goog_1_59114_8);
ZSW_LV_IMG_DECLARE(face_goog_1_59114_9);
ZSW_LV_IMG_DECLARE(face_goog_11_60084_0);
ZSW_LV_IMG_DECLARE(face_goog_12_60913_0);
ZSW_LV_IMG_DECLARE(face_goog_19_61460_0);
ZSW_LV_IMG_DECLARE(face_goog_20_61728_0);
ZSW_LV_IMG_DECLARE(face_goog_20_61728_1);
ZSW_LV_IMG_DECLARE(face_goog_20_61728_2);
ZSW_LV_IMG_DECLARE(face_goog_20_61728_3);
ZSW_LV_IMG_DECLARE(face_goog_20_61728_4);
ZSW_LV_IMG_DECLARE(face_goog_20_61728_5);
ZSW_LV_IMG_DECLARE(face_goog_20_61728_6);
ZSW_LV_IMG_DECLARE(face_goog_21_65400_0);
ZSW_LV_IMG_DECLARE(face_goog_21_65400_1);
ZSW_LV_IMG_DECLARE(face_goog_21_65400_2);
ZSW_LV_IMG_DECLARE(face_goog_21_65400_3);
ZSW_LV_IMG_DECLARE(face_goog_21_65400_4);
ZSW_LV_IMG_DECLARE(face_goog_21_65400_5);
ZSW_LV_IMG_DECLARE(face_goog_21_65400_6);
ZSW_LV_IMG_DECLARE(face_goog_22_72744_0);
ZSW_LV_IMG_DECLARE(face_goog_22_72744_1);
ZSW_LV_IMG_DECLARE(face_goog_22_72744_2);
ZSW_LV_IMG_DECLARE(face_goog_22_72744_3);
ZSW_LV_IMG_DECLARE(face_goog_22_72744_4);
ZSW_LV_IMG_DECLARE(face_goog_22_72744_5);
ZSW_LV_IMG_DECLARE(face_goog_22_72744_6);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_0);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_1);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_2);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_3);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_4);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_5);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_6);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_7);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_8);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_9);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_10);
ZSW_LV_IMG_DECLARE(face_goog_26_78812_11);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_0);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_1);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_2);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_3);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_4);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_5);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_6);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_7);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_8);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_9);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_10);
ZSW_LV_IMG_DECLARE(face_goog_27_87610_11);
ZSW_LV_IMG_DECLARE(face_goog_28_97966_0);
ZSW_LV_IMG_DECLARE(face_goog_28_97966_1);
ZSW_LV_IMG_DECLARE(face_goog_28_97966_2);
ZSW_LV_IMG_DECLARE(face_goog_28_97966_3);
ZSW_LV_IMG_DECLARE(face_goog_28_97966_4);
ZSW_LV_IMG_DECLARE(face_goog_28_97966_5);
ZSW_LV_IMG_DECLARE(face_goog_28_97966_6);
ZSW_LV_IMG_DECLARE(face_goog_28_97966_7);
ZSW_LV_IMG_DECLARE(face_goog_28_97966_8);
ZSW_LV_IMG_DECLARE(face_goog_28_97966_9);
ZSW_LV_IMG_DECLARE(face_goog_32_65535_0);
ZSW_LV_IMG_DECLARE(face_goog_36_130812_0);
ZSW_LV_IMG_DECLARE(face_goog_41_130994_0);
ZSW_LV_IMG_DECLARE(face_goog_42_131564_0);
ZSW_LV_IMG_DECLARE(face_goog_43_132416_0);
ZSW_LV_IMG_DECLARE(face_goog_44_133314_0);
ZSW_LV_IMG_DECLARE(face_goog_45_134124_0);
ZSW_LV_IMG_DECLARE(face_goog_46_134880_0);
ZSW_LV_IMG_DECLARE(face_goog_47_135702_0);
ZSW_LV_IMG_DECLARE(face_goog_48_136588_0);
ZSW_LV_IMG_DECLARE(face_goog_49_137284_0);
ZSW_LV_IMG_DECLARE(face_goog_preview_0);

#if CONFIG_LV_COLOR_DEPTH_16 != 1
#error "CONFIG_LV_COLOR_DEPTH_16 should be 16 bit for watchfaces"
#endif
#if CONFIG_LV_COLOR_16_SWAP != 1
#error "CONFIG_LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif

const void *face_goog_1_59114_group[] = {
    ZSW_LV_IMG_USE(face_goog_1_59114_0),
    ZSW_LV_IMG_USE(face_goog_1_59114_1),
    ZSW_LV_IMG_USE(face_goog_1_59114_2),
    ZSW_LV_IMG_USE(face_goog_1_59114_3),
    ZSW_LV_IMG_USE(face_goog_1_59114_4),
    ZSW_LV_IMG_USE(face_goog_1_59114_5),
    ZSW_LV_IMG_USE(face_goog_1_59114_6),
    ZSW_LV_IMG_USE(face_goog_1_59114_7),
    ZSW_LV_IMG_USE(face_goog_1_59114_8),
    ZSW_LV_IMG_USE(face_goog_1_59114_9),
};
const void *face_goog_20_61728_group[] = {
    ZSW_LV_IMG_USE(face_goog_20_61728_0),
    ZSW_LV_IMG_USE(face_goog_20_61728_1),
    ZSW_LV_IMG_USE(face_goog_20_61728_2),
    ZSW_LV_IMG_USE(face_goog_20_61728_3),
    ZSW_LV_IMG_USE(face_goog_20_61728_4),
    ZSW_LV_IMG_USE(face_goog_20_61728_5),
    ZSW_LV_IMG_USE(face_goog_20_61728_6),
};
const void *face_goog_21_65400_group[] = {
    ZSW_LV_IMG_USE(face_goog_21_65400_0),
    ZSW_LV_IMG_USE(face_goog_21_65400_1),
    ZSW_LV_IMG_USE(face_goog_21_65400_2),
    ZSW_LV_IMG_USE(face_goog_21_65400_3),
    ZSW_LV_IMG_USE(face_goog_21_65400_4),
    ZSW_LV_IMG_USE(face_goog_21_65400_5),
    ZSW_LV_IMG_USE(face_goog_21_65400_6),
};
const void *face_goog_22_72744_group[] = {
    ZSW_LV_IMG_USE(face_goog_22_72744_0),
    ZSW_LV_IMG_USE(face_goog_22_72744_1),
    ZSW_LV_IMG_USE(face_goog_22_72744_2),
    ZSW_LV_IMG_USE(face_goog_22_72744_3),
    ZSW_LV_IMG_USE(face_goog_22_72744_4),
    ZSW_LV_IMG_USE(face_goog_22_72744_5),
    ZSW_LV_IMG_USE(face_goog_22_72744_6),
};
const void *face_goog_26_78812_group[] = {
    ZSW_LV_IMG_USE(face_goog_26_78812_0),
    ZSW_LV_IMG_USE(face_goog_26_78812_1),
    ZSW_LV_IMG_USE(face_goog_26_78812_2),
    ZSW_LV_IMG_USE(face_goog_26_78812_3),
    ZSW_LV_IMG_USE(face_goog_26_78812_4),
    ZSW_LV_IMG_USE(face_goog_26_78812_5),
    ZSW_LV_IMG_USE(face_goog_26_78812_6),
    ZSW_LV_IMG_USE(face_goog_26_78812_7),
    ZSW_LV_IMG_USE(face_goog_26_78812_8),
    ZSW_LV_IMG_USE(face_goog_26_78812_9),
    ZSW_LV_IMG_USE(face_goog_26_78812_10),
    ZSW_LV_IMG_USE(face_goog_26_78812_11),
};
const void *face_goog_27_87610_group[] = {
    ZSW_LV_IMG_USE(face_goog_27_87610_0),
    ZSW_LV_IMG_USE(face_goog_27_87610_1),
    ZSW_LV_IMG_USE(face_goog_27_87610_2),
    ZSW_LV_IMG_USE(face_goog_27_87610_3),
    ZSW_LV_IMG_USE(face_goog_27_87610_4),
    ZSW_LV_IMG_USE(face_goog_27_87610_5),
    ZSW_LV_IMG_USE(face_goog_27_87610_6),
    ZSW_LV_IMG_USE(face_goog_27_87610_7),
    ZSW_LV_IMG_USE(face_goog_27_87610_8),
    ZSW_LV_IMG_USE(face_goog_27_87610_9),
    ZSW_LV_IMG_USE(face_goog_27_87610_10),
    ZSW_LV_IMG_USE(face_goog_27_87610_11),
};
const void *face_goog_28_97966_group[] = {
    ZSW_LV_IMG_USE(face_goog_28_97966_0),
    ZSW_LV_IMG_USE(face_goog_28_97966_1),
    ZSW_LV_IMG_USE(face_goog_28_97966_2),
    ZSW_LV_IMG_USE(face_goog_28_97966_3),
    ZSW_LV_IMG_USE(face_goog_28_97966_4),
    ZSW_LV_IMG_USE(face_goog_28_97966_5),
    ZSW_LV_IMG_USE(face_goog_28_97966_6),
    ZSW_LV_IMG_USE(face_goog_28_97966_7),
    ZSW_LV_IMG_USE(face_goog_28_97966_8),
    ZSW_LV_IMG_USE(face_goog_28_97966_9),
};
const void *face_goog_weather[] = {
    ZSW_LV_IMG_USE(face_goog_41_130994_0),
    ZSW_LV_IMG_USE(face_goog_42_131564_0),
    ZSW_LV_IMG_USE(face_goog_43_132416_0),
    ZSW_LV_IMG_USE(face_goog_44_133314_0),
    ZSW_LV_IMG_USE(face_goog_45_134124_0),
    ZSW_LV_IMG_USE(face_goog_46_134880_0),
    ZSW_LV_IMG_USE(face_goog_47_135702_0),
    ZSW_LV_IMG_USE(face_goog_48_136588_0),
    ZSW_LV_IMG_USE(face_goog_49_137284_0),
};

static int32_t getPlaceValue(int32_t num, int32_t place)
{
    int32_t divisor = 1;
    for (uint32_t i = 1; i < place; i++) {
        divisor *= 10;
    }
    return (num / divisor) % 10;
}

static int32_t setPlaceValue(int32_t num, int32_t place, int32_t newValue)
{
    int32_t divisor = 1;
    for (uint32_t i = 1; i < place; i++) {
        divisor *= 10;
    }
    return num - ((num / divisor) % 10 * divisor) + (newValue * divisor);
}

static void watchface_goog_remove(void)
{
    if (!face_goog) {
        return;
    }

    lv_obj_del(face_goog);
    face_goog = NULL;
}

static void watchface_goog_invalidate_cached(void)
{
    last_date = -1;
    last_day = -1;
    last_month = -1;
    last_year = -1;
    last_weekday = -1;
    last_hour = -1;
    last_minute = -1;
    last_steps = -1;
    last_distance = -1;
    last_kcal = -1;
}

static const void *watchface_goog_get_preview_img(void)
{
    return ZSW_LV_IMG_USE(face_goog_preview_0);
}

static void watchface_goog_set_datetime(int day_of_week, int date, int day, int month, int year, int weekday, int hour,
                                        int minute, int second, uint32_t usec, bool am, bool mode)
{
    if (!face_goog) {
        return;
    }

    if (getPlaceValue(last_weekday, 1) != getPlaceValue(weekday, 1)) {
        last_weekday = setPlaceValue(last_weekday, 1, getPlaceValue(weekday, 1));
        lv_img_set_src(face_goog_22_72744, face_goog_22_72744_group[((weekday + 6) / 1) % 7]);
    }

    if (getPlaceValue(last_day, 1) != getPlaceValue(day, 1)) {
        last_day = setPlaceValue(last_day, 1, getPlaceValue(day, 1));
        lv_img_set_src(face_goog_23_59114, face_goog_1_59114_group[(day / 1) % 10]);
    }

    if (getPlaceValue(last_day, 2) != getPlaceValue(day, 2)) {
        last_day = setPlaceValue(last_day, 2, getPlaceValue(day, 2));
        lv_img_set_src(face_goog_24_59114, face_goog_1_59114_group[(day / 10) % 10]);
    }

    if (getPlaceValue(last_month, 1) != getPlaceValue(month, 1)) {
        last_month = setPlaceValue(last_month, 1, getPlaceValue(month, 1));
        lv_img_set_src(face_goog_27_87610, face_goog_27_87610_group[(month / 1) % 12]);
    }

    if (getPlaceValue(last_hour, 1) != getPlaceValue(hour, 1)) {
        last_hour = setPlaceValue(last_hour, 1, getPlaceValue(hour, 1));
        lv_img_set_src(face_goog_28_97966, face_goog_28_97966_group[(hour / 1) % 10]);
    }

    if (getPlaceValue(last_hour, 2) != getPlaceValue(hour, 2)) {
        last_hour = setPlaceValue(last_hour, 2, getPlaceValue(hour, 2));
        lv_img_set_src(face_goog_29_97966, face_goog_28_97966_group[(hour / 10) % 10]);
    }

    if (getPlaceValue(last_minute, 1) != getPlaceValue(minute, 1)) {
        last_minute = setPlaceValue(last_minute, 1, getPlaceValue(minute, 1));
        lv_img_set_src(face_goog_30_97966, face_goog_28_97966_group[(minute / 1) % 10]);
    }

    if (getPlaceValue(last_minute, 2) != getPlaceValue(minute, 2)) {
        last_minute = setPlaceValue(last_minute, 2, getPlaceValue(minute, 2));
        lv_img_set_src(face_goog_31_97966, face_goog_28_97966_group[(minute / 10) % 10]);
    }

}

static void watchface_goog_set_step(int32_t steps, int32_t distance, int32_t kcal)
{
    if (!face_goog) {
        return;
    }

    if (getPlaceValue(last_steps, 1) != getPlaceValue(steps, 1)) {
        last_steps = setPlaceValue(last_steps, 1, getPlaceValue(steps, 1));
        lv_img_set_src(face_goog_1_59114, face_goog_1_59114_group[(steps / 1) % 10]);
    }

    if (getPlaceValue(last_steps, 2) != getPlaceValue(steps, 2)) {
        last_steps = setPlaceValue(last_steps, 2, getPlaceValue(steps, 2));
        lv_img_set_src(face_goog_2_59114, face_goog_1_59114_group[(steps / 10) % 10]);
    }

    if (getPlaceValue(last_steps, 3) != getPlaceValue(steps, 3)) {
        last_steps = setPlaceValue(last_steps, 3, getPlaceValue(steps, 3));
        lv_img_set_src(face_goog_3_59114, face_goog_1_59114_group[(steps / 100) % 10]);
    }

    if (getPlaceValue(last_steps, 4) != getPlaceValue(steps, 4)) {
        last_steps = setPlaceValue(last_steps, 4, getPlaceValue(steps, 4));
        lv_img_set_src(face_goog_4_59114, face_goog_1_59114_group[(steps / 1000) % 10]);
    }

    if (getPlaceValue(last_steps, 5) != getPlaceValue(steps, 5)) {
        last_steps = setPlaceValue(last_steps, 5, getPlaceValue(steps, 5));
        lv_img_set_src(face_goog_5_59114, face_goog_1_59114_group[(steps / 10000) % 10]);
    }

    if (getPlaceValue(last_kcal, 1) != getPlaceValue(kcal, 1)) {
        last_kcal = setPlaceValue(last_kcal, 1, getPlaceValue(kcal, 1));
        lv_img_set_src(face_goog_6_59114, face_goog_1_59114_group[(kcal / 1) % 10]);
    }

    if (getPlaceValue(last_kcal, 2) != getPlaceValue(kcal, 2)) {
        last_kcal = setPlaceValue(last_kcal, 2, getPlaceValue(kcal, 2));
        lv_img_set_src(face_goog_7_59114, face_goog_1_59114_group[(kcal / 10) % 10]);
    }

    if (getPlaceValue(last_kcal, 3) != getPlaceValue(kcal, 3)) {
        last_kcal = setPlaceValue(last_kcal, 3, getPlaceValue(kcal, 3));
        lv_img_set_src(face_goog_8_59114, face_goog_1_59114_group[(kcal / 100) % 10]);
    }

    if (getPlaceValue(last_kcal, 4) != getPlaceValue(kcal, 4)) {
        last_kcal = setPlaceValue(last_kcal, 4, getPlaceValue(kcal, 4));
        lv_img_set_src(face_goog_9_59114, face_goog_1_59114_group[(kcal / 1000) % 10]);
    }

}

static void watchface_goog_set_hrm(int32_t bpm, int32_t oxygen)
{
    if (!face_goog) {
        return;
    }

    lv_img_set_src(face_goog_13_59114, face_goog_1_59114_group[(bpm / 1) % 10]);
    lv_img_set_src(face_goog_14_59114, face_goog_1_59114_group[(bpm / 10) % 10]);
    lv_img_set_src(face_goog_15_59114, face_goog_1_59114_group[(bpm / 100) % 10]);

}

static void watchface_goog_set_weather(int8_t temp, int icon)
{
    if (!face_goog) {
        return;
    }

    lv_img_set_src(face_goog_34_59114, face_goog_1_59114_group[(temp / 1) % 10]);
    lv_img_set_src(face_goog_35_59114, face_goog_1_59114_group[(temp / 10) % 10]);
    if (temp >= 0) {
        lv_obj_add_flag(face_goog_37_65535, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_clear_flag(face_goog_37_65535, LV_OBJ_FLAG_HIDDEN);
    }
    lv_img_set_src(face_goog_41_130994, face_goog_weather[icon % 8]);

}

static void watchface_goog_set_ble_connected(bool connected)
{
    if (!face_goog) {
        return;
    }

}

static void watchface_goog_set_battery_percent(int32_t percent, int32_t battery)
{
    if (!face_goog) {
        return;
    }

    lv_img_set_src(face_goog_16_59114, face_goog_1_59114_group[(percent / 1) % 10]);
    lv_img_set_src(face_goog_17_59114, face_goog_1_59114_group[(percent / 10) % 10]);
    lv_img_set_src(face_goog_18_59114, face_goog_1_59114_group[(percent / 100) % 10]);
    if (percent < 100) {
        lv_obj_add_flag(face_goog_18_59114, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_clear_flag(face_goog_18_59114, LV_OBJ_FLAG_HIDDEN);
    }
    lv_img_set_src(face_goog_20_61728, face_goog_20_61728_group[(percent / (int)(100 / 7.0) % 7)]);
}

static void watchface_goog_set_num_notifcations(int32_t number)
{
    if (!face_goog) {
        return;
    }

}

static void watchface_goog_set_watch_env_sensors(int temperature, int humidity, int pressure, float iaq, float co2)
{
    if (!face_goog) {
        return;
    }

}

void watchface_goog_show(watchface_app_evt_listener evt_cb, zsw_settings_watchface_t *settings)
{
    ui_goog_evt_cb = evt_cb;

    lv_obj_clear_flag(lv_scr_act(), LV_OBJ_FLAG_SCROLLABLE);
    face_goog = lv_obj_create(lv_scr_act());
    watchface_goog_invalidate_cached();

    lv_obj_clear_flag(face_goog, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scrollbar_mode(face_goog, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_opa(face_goog, LV_OPA_TRANSP, LV_PART_MAIN);

    lv_obj_set_style_border_width(face_goog, 0, LV_PART_MAIN);
    lv_obj_set_size(face_goog, 240, 240);
    lv_obj_clear_flag(face_goog, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_goog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_goog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_goog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_goog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_goog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_goog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_goog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    face_goog_0_1004 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_0_1004, ZSW_LV_IMG_USE(face_goog_0_1004_0));
    lv_obj_set_width(face_goog_0_1004, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_0_1004, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_0_1004, 0);
    lv_obj_set_y(face_goog_0_1004, 0);
    lv_obj_add_flag(face_goog_0_1004, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_0_1004, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_1_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_1_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_1_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_1_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_1_59114, 118);
    lv_obj_set_y(face_goog_1_59114, 194);
    lv_obj_add_flag(face_goog_1_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_1_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_2_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_2_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_2_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_2_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_2_59114, 111);
    lv_obj_set_y(face_goog_2_59114, 194);
    lv_obj_add_flag(face_goog_2_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_2_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_3_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_3_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_3_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_3_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_3_59114, 104);
    lv_obj_set_y(face_goog_3_59114, 194);
    lv_obj_add_flag(face_goog_3_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_3_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_4_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_4_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_4_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_4_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_4_59114, 96);
    lv_obj_set_y(face_goog_4_59114, 194);
    lv_obj_add_flag(face_goog_4_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_4_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_5_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_5_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_5_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_5_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_5_59114, 89);
    lv_obj_set_y(face_goog_5_59114, 194);
    lv_obj_add_flag(face_goog_5_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_5_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_6_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_6_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_6_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_6_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_6_59114, 146);
    lv_obj_set_y(face_goog_6_59114, 168);
    lv_obj_add_flag(face_goog_6_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_6_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_7_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_7_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_7_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_7_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_7_59114, 139);
    lv_obj_set_y(face_goog_7_59114, 168);
    lv_obj_add_flag(face_goog_7_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_7_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_8_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_8_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_8_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_8_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_8_59114, 132);
    lv_obj_set_y(face_goog_8_59114, 168);
    lv_obj_add_flag(face_goog_8_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_8_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_9_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_9_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_9_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_9_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_9_59114, 124);
    lv_obj_set_y(face_goog_9_59114, 168);
    lv_obj_add_flag(face_goog_9_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_9_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_12_60913 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_12_60913, ZSW_LV_IMG_USE(face_goog_12_60913_0));
    lv_obj_set_width(face_goog_12_60913, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_12_60913, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_12_60913, 128);
    lv_obj_set_y(face_goog_12_60913, 194);
    lv_obj_add_flag(face_goog_12_60913, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_12_60913, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_13_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_13_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_13_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_13_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_13_59114, 104);
    lv_obj_set_y(face_goog_13_59114, 168);
    lv_obj_add_flag(face_goog_13_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_13_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_14_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_14_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_14_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_14_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_14_59114, 96);
    lv_obj_set_y(face_goog_14_59114, 168);
    lv_obj_add_flag(face_goog_14_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_14_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_15_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_15_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_15_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_15_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_15_59114, 89);
    lv_obj_set_y(face_goog_15_59114, 168);
    lv_obj_add_flag(face_goog_15_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_15_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_16_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_16_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_16_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_16_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_16_59114, 172);
    lv_obj_set_y(face_goog_16_59114, 168);
    lv_obj_add_flag(face_goog_16_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_16_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_17_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_17_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_17_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_17_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_17_59114, 165);
    lv_obj_set_y(face_goog_17_59114, 168);
    lv_obj_add_flag(face_goog_17_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_17_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_18_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_18_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_18_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_18_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_18_59114, 160);
    lv_obj_set_y(face_goog_18_59114, 168);
    lv_obj_add_flag(face_goog_18_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_18_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_19_61460 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_19_61460, ZSW_LV_IMG_USE(face_goog_19_61460_0));
    lv_obj_set_width(face_goog_19_61460, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_19_61460, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_19_61460, 180);
    lv_obj_set_y(face_goog_19_61460, 168);
    lv_obj_add_flag(face_goog_19_61460, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_19_61460, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_20_61728 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_20_61728, ZSW_LV_IMG_USE(face_goog_20_61728_0));
    lv_obj_set_width(face_goog_20_61728, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_20_61728, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_20_61728, 162);
    lv_obj_set_y(face_goog_20_61728, 147);
    lv_obj_add_flag(face_goog_20_61728, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_20_61728, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_22_72744 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_22_72744, ZSW_LV_IMG_USE(face_goog_22_72744_0));
    lv_obj_set_width(face_goog_22_72744, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_22_72744, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_22_72744, 44);
    lv_obj_set_y(face_goog_22_72744, 120);
    lv_obj_add_flag(face_goog_22_72744, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_22_72744, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_23_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_23_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_23_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_23_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_23_59114, 120);
    lv_obj_set_y(face_goog_23_59114, 120);
    lv_obj_add_flag(face_goog_23_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_23_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_24_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_24_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_24_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_24_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_24_59114, 113);
    lv_obj_set_y(face_goog_24_59114, 120);
    lv_obj_add_flag(face_goog_24_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_24_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_27_87610 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_27_87610, ZSW_LV_IMG_USE(face_goog_27_87610_0));
    lv_obj_set_width(face_goog_27_87610, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_27_87610, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_27_87610, 128);
    lv_obj_set_y(face_goog_27_87610, 120);
    lv_obj_add_flag(face_goog_27_87610, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_27_87610, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_28_97966 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_28_97966, ZSW_LV_IMG_USE(face_goog_28_97966_0));
    lv_obj_set_width(face_goog_28_97966, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_28_97966, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_28_97966, 74);
    lv_obj_set_y(face_goog_28_97966, 53);
    lv_obj_add_flag(face_goog_28_97966, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_28_97966, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_29_97966 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_29_97966, ZSW_LV_IMG_USE(face_goog_28_97966_0));
    lv_obj_set_width(face_goog_29_97966, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_29_97966, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_29_97966, 33);
    lv_obj_set_y(face_goog_29_97966, 53);
    lv_obj_add_flag(face_goog_29_97966, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_29_97966, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_30_97966 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_30_97966, ZSW_LV_IMG_USE(face_goog_28_97966_0));
    lv_obj_set_width(face_goog_30_97966, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_30_97966, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_30_97966, 165);
    lv_obj_set_y(face_goog_30_97966, 53);
    lv_obj_add_flag(face_goog_30_97966, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_30_97966, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_31_97966 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_31_97966, ZSW_LV_IMG_USE(face_goog_28_97966_0));
    lv_obj_set_width(face_goog_31_97966, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_31_97966, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_31_97966, 124);
    lv_obj_set_y(face_goog_31_97966, 53);
    lv_obj_add_flag(face_goog_31_97966, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_31_97966, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_34_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_34_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_34_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_34_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_34_59114, 60);
    lv_obj_set_y(face_goog_34_59114, 168);
    lv_obj_add_flag(face_goog_34_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_34_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_35_59114 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_35_59114, ZSW_LV_IMG_USE(face_goog_1_59114_0));
    lv_obj_set_width(face_goog_35_59114, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_35_59114, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_35_59114, 52);
    lv_obj_set_y(face_goog_35_59114, 168);
    lv_obj_add_flag(face_goog_35_59114, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_35_59114, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_36_130812 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_36_130812, ZSW_LV_IMG_USE(face_goog_36_130812_0));
    lv_obj_set_width(face_goog_36_130812, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_36_130812, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_36_130812, 67);
    lv_obj_set_y(face_goog_36_130812, 168);
    lv_obj_add_flag(face_goog_36_130812, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_36_130812, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_37_65535 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_37_65535, ZSW_LV_IMG_USE(face_goog_32_65535_0));
    lv_obj_set_width(face_goog_37_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_37_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_37_65535, 46);
    lv_obj_set_y(face_goog_37_65535, 174);
    lv_obj_add_flag(face_goog_37_65535, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_37_65535, LV_OBJ_FLAG_SCROLLABLE);

    face_goog_41_130994 = lv_img_create(face_goog);
    lv_img_set_src(face_goog_41_130994, ZSW_LV_IMG_USE(face_goog_41_130994_0));
    lv_obj_set_width(face_goog_41_130994, LV_SIZE_CONTENT);
    lv_obj_set_height(face_goog_41_130994, LV_SIZE_CONTENT);
    lv_obj_set_x(face_goog_41_130994, 50);
    lv_obj_set_y(face_goog_41_130994, 146);
    lv_obj_add_flag(face_goog_41_130994, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_goog_41_130994, LV_OBJ_FLAG_SCROLLABLE);

}

static watchface_ui_api_t ui_api = {
    .show = watchface_goog_show,
    .remove = watchface_goog_remove,
    .set_battery_percent = watchface_goog_set_battery_percent,
    .set_hrm = watchface_goog_set_hrm,
    .set_step = watchface_goog_set_step,
    .set_ble_connected = watchface_goog_set_ble_connected,
    .set_num_notifcations = watchface_goog_set_num_notifcations,
    .set_weather = watchface_goog_set_weather,
    .set_datetime = watchface_goog_set_datetime,
    .set_watch_env_sensors = watchface_goog_set_watch_env_sensors,
    .ui_invalidate_cached = watchface_goog_invalidate_cached,
    .get_preview_img = watchface_goog_get_preview_img,
    .name = "Pixel"
};

static int watchface_goog_init(void)
{
    watchface_app_register_ui(&ui_api);

    return 0;
}

SYS_INIT(watchface_goog_init, APPLICATION, WATCHFACE_UI_INIT_PRIO);
