
// File generated by bin2lvgl
// developed by fbiego.
// https://github.com/fbiego
// modified by Daniel Kampert.
// https://github.com/kampi
// Watchface: 79_2_dial

#include <lvgl.h>

#include <zephyr/logging/log.h>

#include "ui/zsw_ui.h"
#include "applications/watchface/watchface_app.h"
#include "ui/watchfaces/zsw_ui_notification_area.h"

LOG_MODULE_REGISTER(watchface_79_2_dial, LOG_LEVEL_WRN);

static lv_obj_t *face_79_2_dial;
static lv_obj_t *face_79_2_dial = NULL;
static watchface_app_evt_listener ui_79_2_dial_evt_cb;
static zsw_ui_notification_area_t *zsw_ui_notifications_area;

static int last_date = -1;
static int last_day = -1;
static int last_month = -1;
static int last_year = -1;
static int last_weekday = -1;
static int last_hour = -1;
static int last_minute = -1;

static int last_steps = -1;
static int last_distance = -1;
static int last_kcal = -1;

static lv_obj_t *face_79_2_dial_0_404;
static lv_obj_t *face_79_2_dial_1_59582;
static lv_obj_t *face_79_2_dial_2_59582;
static lv_obj_t *face_79_2_dial_3_123330;
static lv_obj_t *face_79_2_dial_4_123330;
static lv_obj_t *face_79_2_dial_5_58512;
static lv_obj_t *face_79_2_dial_6_58512;
static lv_obj_t *face_79_2_dial_7_58512;
static lv_obj_t *face_79_2_dial_8_58512;
static lv_obj_t *face_79_2_dial_9_59456;
static lv_obj_t *face_79_2_dial_10_58512;
static lv_obj_t *face_79_2_dial_11_58512;
static lv_obj_t *face_79_2_dial_12_58512;
static lv_obj_t *face_79_2_dial_13_58512;
static lv_obj_t *face_79_2_dial_14_58512;
static lv_obj_t *face_79_2_dial_15_58512;
static lv_obj_t *face_79_2_dial_16_58512;
static lv_obj_t *face_79_2_dial_17_58512;
static lv_obj_t *face_79_2_dial_19_144206;

ZSW_LV_IMG_DECLARE(face_79_2_dial_0_404_0);
ZSW_LV_IMG_DECLARE(face_79_2_dial_1_59582_0);
ZSW_LV_IMG_DECLARE(face_79_2_dial_1_59582_1);
ZSW_LV_IMG_DECLARE(face_79_2_dial_1_59582_2);
ZSW_LV_IMG_DECLARE(face_79_2_dial_1_59582_3);
ZSW_LV_IMG_DECLARE(face_79_2_dial_1_59582_4);
ZSW_LV_IMG_DECLARE(face_79_2_dial_1_59582_5);
ZSW_LV_IMG_DECLARE(face_79_2_dial_1_59582_6);
ZSW_LV_IMG_DECLARE(face_79_2_dial_1_59582_7);
ZSW_LV_IMG_DECLARE(face_79_2_dial_1_59582_8);
ZSW_LV_IMG_DECLARE(face_79_2_dial_1_59582_9);
ZSW_LV_IMG_DECLARE(face_79_2_dial_3_123330_0);
ZSW_LV_IMG_DECLARE(face_79_2_dial_3_123330_1);
ZSW_LV_IMG_DECLARE(face_79_2_dial_3_123330_2);
ZSW_LV_IMG_DECLARE(face_79_2_dial_3_123330_3);
ZSW_LV_IMG_DECLARE(face_79_2_dial_3_123330_4);
ZSW_LV_IMG_DECLARE(face_79_2_dial_3_123330_5);
ZSW_LV_IMG_DECLARE(face_79_2_dial_3_123330_6);
ZSW_LV_IMG_DECLARE(face_79_2_dial_3_123330_7);
ZSW_LV_IMG_DECLARE(face_79_2_dial_3_123330_8);
ZSW_LV_IMG_DECLARE(face_79_2_dial_3_123330_9);
ZSW_LV_IMG_DECLARE(face_79_2_dial_5_58512_0);
ZSW_LV_IMG_DECLARE(face_79_2_dial_5_58512_1);
ZSW_LV_IMG_DECLARE(face_79_2_dial_5_58512_2);
ZSW_LV_IMG_DECLARE(face_79_2_dial_5_58512_3);
ZSW_LV_IMG_DECLARE(face_79_2_dial_5_58512_4);
ZSW_LV_IMG_DECLARE(face_79_2_dial_5_58512_5);
ZSW_LV_IMG_DECLARE(face_79_2_dial_5_58512_6);
ZSW_LV_IMG_DECLARE(face_79_2_dial_5_58512_7);
ZSW_LV_IMG_DECLARE(face_79_2_dial_5_58512_8);
ZSW_LV_IMG_DECLARE(face_79_2_dial_5_58512_9);
ZSW_LV_IMG_DECLARE(face_79_2_dial_9_59456_0);
ZSW_LV_IMG_DECLARE(face_79_2_dial_18_138796_0);
ZSW_LV_IMG_DECLARE(face_79_2_dial_18_138796_1);
ZSW_LV_IMG_DECLARE(face_79_2_dial_18_138796_2);
ZSW_LV_IMG_DECLARE(face_79_2_dial_18_138796_3);
ZSW_LV_IMG_DECLARE(face_79_2_dial_18_138796_4);
ZSW_LV_IMG_DECLARE(face_79_2_dial_18_138796_5);
ZSW_LV_IMG_DECLARE(face_79_2_dial_18_138796_6);
ZSW_LV_IMG_DECLARE(face_79_2_dial_19_144206_0);
ZSW_LV_IMG_DECLARE(face_79_2_dial_19_144206_1);
ZSW_LV_IMG_DECLARE(face_79_2_dial_19_144206_2);
ZSW_LV_IMG_DECLARE(face_79_2_dial_19_144206_3);
ZSW_LV_IMG_DECLARE(face_79_2_dial_19_144206_4);
ZSW_LV_IMG_DECLARE(face_79_2_dial_19_144206_5);
ZSW_LV_IMG_DECLARE(face_79_2_dial_19_144206_6);
ZSW_LV_IMG_DECLARE(face_79_2_dial_preview_0);

#if CONFIG_LV_COLOR_DEPTH_16 != 1
#error "CONFIG_LV_COLOR_DEPTH_16 should be 16 bit for watchfaces"
#endif
#if CONFIG_LV_COLOR_16_SWAP != 1
#error "CONFIG_LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif

const void *face_79_2_dial_1_59582_group[] = {
    ZSW_LV_IMG_USE(face_79_2_dial_1_59582_0),
    ZSW_LV_IMG_USE(face_79_2_dial_1_59582_1),
    ZSW_LV_IMG_USE(face_79_2_dial_1_59582_2),
    ZSW_LV_IMG_USE(face_79_2_dial_1_59582_3),
    ZSW_LV_IMG_USE(face_79_2_dial_1_59582_4),
    ZSW_LV_IMG_USE(face_79_2_dial_1_59582_5),
    ZSW_LV_IMG_USE(face_79_2_dial_1_59582_6),
    ZSW_LV_IMG_USE(face_79_2_dial_1_59582_7),
    ZSW_LV_IMG_USE(face_79_2_dial_1_59582_8),
    ZSW_LV_IMG_USE(face_79_2_dial_1_59582_9),
};
const void *face_79_2_dial_3_123330_group[] = {
    ZSW_LV_IMG_USE(face_79_2_dial_3_123330_0),
    ZSW_LV_IMG_USE(face_79_2_dial_3_123330_1),
    ZSW_LV_IMG_USE(face_79_2_dial_3_123330_2),
    ZSW_LV_IMG_USE(face_79_2_dial_3_123330_3),
    ZSW_LV_IMG_USE(face_79_2_dial_3_123330_4),
    ZSW_LV_IMG_USE(face_79_2_dial_3_123330_5),
    ZSW_LV_IMG_USE(face_79_2_dial_3_123330_6),
    ZSW_LV_IMG_USE(face_79_2_dial_3_123330_7),
    ZSW_LV_IMG_USE(face_79_2_dial_3_123330_8),
    ZSW_LV_IMG_USE(face_79_2_dial_3_123330_9),
};
const void *face_79_2_dial_5_58512_group[] = {
    ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0),
    ZSW_LV_IMG_USE(face_79_2_dial_5_58512_1),
    ZSW_LV_IMG_USE(face_79_2_dial_5_58512_2),
    ZSW_LV_IMG_USE(face_79_2_dial_5_58512_3),
    ZSW_LV_IMG_USE(face_79_2_dial_5_58512_4),
    ZSW_LV_IMG_USE(face_79_2_dial_5_58512_5),
    ZSW_LV_IMG_USE(face_79_2_dial_5_58512_6),
    ZSW_LV_IMG_USE(face_79_2_dial_5_58512_7),
    ZSW_LV_IMG_USE(face_79_2_dial_5_58512_8),
    ZSW_LV_IMG_USE(face_79_2_dial_5_58512_9),
};
const void *face_79_2_dial_18_138796_group[] = {
    ZSW_LV_IMG_USE(face_79_2_dial_18_138796_0),
    ZSW_LV_IMG_USE(face_79_2_dial_18_138796_1),
    ZSW_LV_IMG_USE(face_79_2_dial_18_138796_2),
    ZSW_LV_IMG_USE(face_79_2_dial_18_138796_3),
    ZSW_LV_IMG_USE(face_79_2_dial_18_138796_4),
    ZSW_LV_IMG_USE(face_79_2_dial_18_138796_5),
    ZSW_LV_IMG_USE(face_79_2_dial_18_138796_6),
};
const void *face_79_2_dial_19_144206_group[] = {
    ZSW_LV_IMG_USE(face_79_2_dial_19_144206_0),
    ZSW_LV_IMG_USE(face_79_2_dial_19_144206_1),
    ZSW_LV_IMG_USE(face_79_2_dial_19_144206_2),
    ZSW_LV_IMG_USE(face_79_2_dial_19_144206_3),
    ZSW_LV_IMG_USE(face_79_2_dial_19_144206_4),
    ZSW_LV_IMG_USE(face_79_2_dial_19_144206_5),
    ZSW_LV_IMG_USE(face_79_2_dial_19_144206_6),
};

static int32_t getPlaceValue(int32_t num, int32_t place)
{
    int32_t divisor = 1;
    for (uint32_t i = 1; i < place; i++) {
        divisor *= 10;
    }
    return (num / divisor) % 10;
}

static int32_t setPlaceValue(int32_t num, int32_t place, int32_t newValue)
{
    int32_t divisor = 1;
    for (uint32_t i = 1; i < place; i++) {
        divisor *= 10;
    }
    return num - ((num / divisor) % 10 * divisor) + (newValue * divisor);
}

static void watchface_79_2_dial_remove(void)
{
    if (!face_79_2_dial) {
        return;
    }

    lv_obj_del(face_79_2_dial);
    face_79_2_dial = NULL;
}

static void watchface_79_2_dial_invalidate_cached(void)
{
    last_date = -1;
    last_day = -1;
    last_month = -1;
    last_year = -1;
    last_weekday = -1;
    last_hour = -1;
    last_minute = -1;
    last_steps = -1;
    last_distance = -1;
    last_kcal = -1;
}

static const void *watchface_79_2_dial_get_preview_img(void)
{
    return ZSW_LV_IMG_USE(face_79_2_dial_preview_0);
}

static void watchface_79_2_dial_set_datetime(int day_of_week, int date, int day, int month, int year, int weekday,
                                             int hour,
                                             int minute, int second, uint32_t usec, bool am, bool mode)
{
    if (!face_79_2_dial) {
        return;
    }

    if (getPlaceValue(last_hour, 1) != getPlaceValue(hour, 1)) {
        last_hour = setPlaceValue(last_hour, 1, getPlaceValue(hour, 1));
        lv_img_set_src(face_79_2_dial_1_59582, face_79_2_dial_1_59582_group[(hour / 1) % 10]);
    }

    if (getPlaceValue(last_hour, 2) != getPlaceValue(hour, 2)) {
        last_hour = setPlaceValue(last_hour, 2, getPlaceValue(hour, 2));
        lv_img_set_src(face_79_2_dial_2_59582, face_79_2_dial_1_59582_group[(hour / 10) % 10]);
    }

    if (getPlaceValue(last_minute, 1) != getPlaceValue(minute, 1)) {
        last_minute = setPlaceValue(last_minute, 1, getPlaceValue(minute, 1));
        lv_img_set_src(face_79_2_dial_3_123330, face_79_2_dial_3_123330_group[(minute / 1) % 10]);
    }

    if (getPlaceValue(last_minute, 2) != getPlaceValue(minute, 2)) {
        last_minute = setPlaceValue(last_minute, 2, getPlaceValue(minute, 2));
        lv_img_set_src(face_79_2_dial_4_123330, face_79_2_dial_3_123330_group[(minute / 10) % 10]);
    }

    if (getPlaceValue(last_month, 1) != getPlaceValue(month, 1)) {
        last_month = setPlaceValue(last_month, 1, getPlaceValue(month, 1));
        lv_img_set_src(face_79_2_dial_5_58512, face_79_2_dial_5_58512_group[(month / 1) % 10]);
    }

    if (getPlaceValue(last_month, 2) != getPlaceValue(month, 2)) {
        last_month = setPlaceValue(last_month, 2, getPlaceValue(month, 2));
        lv_img_set_src(face_79_2_dial_6_58512, face_79_2_dial_5_58512_group[(month / 10) % 10]);
    }

    if (getPlaceValue(last_day, 1) != getPlaceValue(day, 1)) {
        last_day = setPlaceValue(last_day, 1, getPlaceValue(day, 1));
        lv_img_set_src(face_79_2_dial_7_58512, face_79_2_dial_5_58512_group[(day / 1) % 10]);
    }

    if (getPlaceValue(last_day, 2) != getPlaceValue(day, 2)) {
        last_day = setPlaceValue(last_day, 2, getPlaceValue(day, 2));
        lv_img_set_src(face_79_2_dial_8_58512, face_79_2_dial_5_58512_group[(day / 10) % 10]);
    }

    if (getPlaceValue(last_weekday, 1) != getPlaceValue(weekday, 1)) {
        last_weekday = setPlaceValue(last_weekday, 1, getPlaceValue(weekday, 1));
        lv_img_set_src(face_79_2_dial_19_144206, face_79_2_dial_19_144206_group[((weekday + 6) / 1) % 7]);
    }

}

static void watchface_79_2_dial_set_step(int32_t steps, int32_t distance, int32_t kcal)
{
    if (!face_79_2_dial) {
        return;
    }

    if (getPlaceValue(last_steps, 1) != getPlaceValue(steps, 1)) {
        last_steps = setPlaceValue(last_steps, 1, getPlaceValue(steps, 1));
        lv_img_set_src(face_79_2_dial_13_58512, face_79_2_dial_5_58512_group[(steps / 1) % 10]);
    }

    if (getPlaceValue(last_steps, 2) != getPlaceValue(steps, 2)) {
        last_steps = setPlaceValue(last_steps, 2, getPlaceValue(steps, 2));
        lv_img_set_src(face_79_2_dial_14_58512, face_79_2_dial_5_58512_group[(steps / 10) % 10]);
    }

    if (getPlaceValue(last_steps, 3) != getPlaceValue(steps, 3)) {
        last_steps = setPlaceValue(last_steps, 3, getPlaceValue(steps, 3));
        lv_img_set_src(face_79_2_dial_15_58512, face_79_2_dial_5_58512_group[(steps / 100) % 10]);
    }

    if (getPlaceValue(last_steps, 4) != getPlaceValue(steps, 4)) {
        last_steps = setPlaceValue(last_steps, 4, getPlaceValue(steps, 4));
        lv_img_set_src(face_79_2_dial_16_58512, face_79_2_dial_5_58512_group[(steps / 1000) % 10]);
    }

    if (getPlaceValue(last_steps, 5) != getPlaceValue(steps, 5)) {
        last_steps = setPlaceValue(last_steps, 5, getPlaceValue(steps, 5));
        lv_img_set_src(face_79_2_dial_17_58512, face_79_2_dial_5_58512_group[(steps / 10000) % 10]);
    }

}

static void watchface_79_2_dial_set_hrm(int32_t bpm, int32_t oxygen)
{
    if (!face_79_2_dial) {
        return;
    }

}

static void watchface_79_2_dial_set_weather(int8_t temp, int icon)
{
    if (!face_79_2_dial) {
        return;
    }

}

static void watchface_79_2_dial_set_ble_connected(bool connected)
{
    if (!face_79_2_dial) {
        return;
    }

    zsw_ui_notification_area_ble_connected(zsw_ui_notifications_area, connected);
}

static void watchface_79_2_dial_set_battery_percent(int32_t percent, int32_t battery)
{
    if (!face_79_2_dial) {
        return;
    }

    lv_img_set_src(face_79_2_dial_10_58512, face_79_2_dial_5_58512_group[(percent / 1) % 10]);
    lv_img_set_src(face_79_2_dial_11_58512, face_79_2_dial_5_58512_group[(percent / 10) % 10]);
    lv_img_set_src(face_79_2_dial_12_58512, face_79_2_dial_5_58512_group[(percent / 100) % 10]);
    if (percent < 100) {
        lv_obj_add_flag(face_79_2_dial_12_58512, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_clear_flag(face_79_2_dial_12_58512, LV_OBJ_FLAG_HIDDEN);
    }

}

static void watchface_79_2_dial_set_num_notifcations(int32_t number)
{
    if (!face_79_2_dial) {
        return;
    }

    zsw_ui_notification_area_num_notifications(zsw_ui_notifications_area, number);
}

static void watchface_79_2_dial_set_watch_env_sensors(int temperature, int humidity, int pressure, float iaq, float co2)
{
    if (!face_79_2_dial) {
        return;
    }

}

void watchface_79_2_dial_show(lv_obj_t *parent, watchface_app_evt_listener evt_cb, zsw_settings_watchface_t *settings)
{
    ui_79_2_dial_evt_cb = evt_cb;

    lv_obj_clear_flag(parent, LV_OBJ_FLAG_SCROLLABLE);
    face_79_2_dial = lv_obj_create(parent);
    watchface_79_2_dial_invalidate_cached();

    lv_obj_clear_flag(face_79_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scrollbar_mode(face_79_2_dial, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_opa(face_79_2_dial, LV_OPA_TRANSP, LV_PART_MAIN);

    lv_obj_set_style_border_width(face_79_2_dial, 0, LV_PART_MAIN);
    lv_obj_set_size(face_79_2_dial, 240, 240);
    lv_obj_clear_flag(face_79_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_79_2_dial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_79_2_dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_79_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_79_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_79_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_79_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_79_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    face_79_2_dial_0_404 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_0_404, ZSW_LV_IMG_USE(face_79_2_dial_0_404_0));
    lv_obj_set_width(face_79_2_dial_0_404, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_0_404, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_0_404, 0);
    lv_obj_set_y(face_79_2_dial_0_404, 0);
    lv_obj_add_flag(face_79_2_dial_0_404, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_0_404, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_1_59582 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_1_59582, ZSW_LV_IMG_USE(face_79_2_dial_1_59582_0));
    lv_obj_set_width(face_79_2_dial_1_59582, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_1_59582, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_1_59582, 82);
    lv_obj_set_y(face_79_2_dial_1_59582, 69);
    lv_obj_add_flag(face_79_2_dial_1_59582, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_1_59582, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_2_59582 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_2_59582, ZSW_LV_IMG_USE(face_79_2_dial_1_59582_0));
    lv_obj_set_width(face_79_2_dial_2_59582, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_2_59582, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_2_59582, 14);
    lv_obj_set_y(face_79_2_dial_2_59582, 69);
    lv_obj_add_flag(face_79_2_dial_2_59582, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_2_59582, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_3_123330 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_3_123330, ZSW_LV_IMG_USE(face_79_2_dial_3_123330_0));
    lv_obj_set_width(face_79_2_dial_3_123330, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_3_123330, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_3_123330, 188);
    lv_obj_set_y(face_79_2_dial_3_123330, 93);
    lv_obj_add_flag(face_79_2_dial_3_123330, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_3_123330, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_4_123330 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_4_123330, ZSW_LV_IMG_USE(face_79_2_dial_3_123330_0));
    lv_obj_set_width(face_79_2_dial_4_123330, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_4_123330, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_4_123330, 154);
    lv_obj_set_y(face_79_2_dial_4_123330, 93);
    lv_obj_add_flag(face_79_2_dial_4_123330, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_4_123330, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_5_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_5_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_5_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_5_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_5_58512, 108);
    lv_obj_set_y(face_79_2_dial_5_58512, 211);
    lv_obj_add_flag(face_79_2_dial_5_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_5_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_6_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_6_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_6_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_6_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_6_58512, 99);
    lv_obj_set_y(face_79_2_dial_6_58512, 211);
    lv_obj_add_flag(face_79_2_dial_6_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_6_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_7_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_7_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_7_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_7_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_7_58512, 133);
    lv_obj_set_y(face_79_2_dial_7_58512, 211);
    lv_obj_add_flag(face_79_2_dial_7_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_7_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_8_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_8_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_8_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_8_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_8_58512, 124);
    lv_obj_set_y(face_79_2_dial_8_58512, 211);
    lv_obj_add_flag(face_79_2_dial_8_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_8_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_9_59456 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_9_59456, ZSW_LV_IMG_USE(face_79_2_dial_9_59456_0));
    lv_obj_set_width(face_79_2_dial_9_59456, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_9_59456, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_9_59456, 116);
    lv_obj_set_y(face_79_2_dial_9_59456, 212);
    lv_obj_add_flag(face_79_2_dial_9_59456, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_9_59456, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_10_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_10_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_10_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_10_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_10_58512, 67);
    lv_obj_set_y(face_79_2_dial_10_58512, 189);
    lv_obj_add_flag(face_79_2_dial_10_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_10_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_11_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_11_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_11_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_11_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_11_58512, 58);
    lv_obj_set_y(face_79_2_dial_11_58512, 189);
    lv_obj_add_flag(face_79_2_dial_11_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_11_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_12_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_12_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_12_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_12_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_12_58512, 49);
    lv_obj_set_y(face_79_2_dial_12_58512, 189);
    lv_obj_add_flag(face_79_2_dial_12_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_12_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_13_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_13_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_13_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_13_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_13_58512, 195);
    lv_obj_set_y(face_79_2_dial_13_58512, 189);
    lv_obj_add_flag(face_79_2_dial_13_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_13_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_14_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_14_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_14_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_14_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_14_58512, 186);
    lv_obj_set_y(face_79_2_dial_14_58512, 189);
    lv_obj_add_flag(face_79_2_dial_14_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_14_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_15_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_15_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_15_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_15_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_15_58512, 177);
    lv_obj_set_y(face_79_2_dial_15_58512, 189);
    lv_obj_add_flag(face_79_2_dial_15_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_15_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_16_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_16_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_16_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_16_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_16_58512, 168);
    lv_obj_set_y(face_79_2_dial_16_58512, 189);
    lv_obj_add_flag(face_79_2_dial_16_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_16_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_17_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_17_58512, ZSW_LV_IMG_USE(face_79_2_dial_5_58512_0));
    lv_obj_set_width(face_79_2_dial_17_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_17_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_17_58512, 159);
    lv_obj_set_y(face_79_2_dial_17_58512, 189);
    lv_obj_add_flag(face_79_2_dial_17_58512, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_17_58512, LV_OBJ_FLAG_SCROLLABLE);

    face_79_2_dial_19_144206 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_19_144206, ZSW_LV_IMG_USE(face_79_2_dial_19_144206_0));
    lv_obj_set_width(face_79_2_dial_19_144206, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_19_144206, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_19_144206, 74);
    lv_obj_set_y(face_79_2_dial_19_144206, 23);
    lv_obj_add_flag(face_79_2_dial_19_144206, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_79_2_dial_19_144206, LV_OBJ_FLAG_SCROLLABLE);

    zsw_ui_notifications_area = zsw_ui_notification_area_add(face_79_2_dial);
    lv_obj_set_pos(zsw_ui_notifications_area->ui_notifications_container, 0, 50);
}

static watchface_ui_api_t ui_api = {
    .show = watchface_79_2_dial_show,
    .remove = watchface_79_2_dial_remove,
    .set_battery_percent = watchface_79_2_dial_set_battery_percent,
    .set_hrm = watchface_79_2_dial_set_hrm,
    .set_step = watchface_79_2_dial_set_step,
    .set_ble_connected = watchface_79_2_dial_set_ble_connected,
    .set_num_notifcations = watchface_79_2_dial_set_num_notifcations,
    .set_weather = watchface_79_2_dial_set_weather,
    .set_datetime = watchface_79_2_dial_set_datetime,
    .set_watch_env_sensors = watchface_79_2_dial_set_watch_env_sensors,
    .ui_invalidate_cached = watchface_79_2_dial_invalidate_cached,
    .get_preview_img = watchface_79_2_dial_get_preview_img,
    .name = "Digital Rough"
};

static int watchface_79_2_dial_init(void)
{
    watchface_app_register_ui(&ui_api);

    return 0;
}

SYS_INIT(watchface_79_2_dial_init, APPLICATION, WATCHFACE_UI_INIT_PRIO);
