
// File generated by bin2lvgl
// developed by fbiego.
// https://github.com/fbiego
// modified by Daniel Kampert.
// https://github.com/kampi
// Watchface: 70_2_dial

#include <lvgl.h>

#include <zephyr/logging/log.h>

#include "ui/zsw_ui.h"
#include "applications/watchface/watchface_app.h"

LOG_MODULE_REGISTER(watchface_70_2_dial, LOG_LEVEL_WRN);

static lv_obj_t *face_70_2_dial;
static lv_obj_t *face_70_2_dial = NULL;
static watchface_app_evt_listener ui_70_2_dial_evt_cb;

static int last_date = -1;
static int last_day = -1;
static int last_month = -1;
static int last_year = -1;
static int last_weekday = -1;
static int last_hour = -1;
static int last_minute = -1;

static int last_steps = -1;
static int last_distance = -1;
static int last_kcal = -1;

static lv_obj_t *face_70_2_dial_0_1224;
static lv_obj_t *face_70_2_dial_1_125929;
static lv_obj_t *face_70_2_dial_2_125929;
static lv_obj_t *face_70_2_dial_3_125929;
static lv_obj_t *face_70_2_dial_4_125929;
static lv_obj_t *face_70_2_dial_5_59328;
static lv_obj_t *face_70_2_dial_6_59328;
static lv_obj_t *face_70_2_dial_7_59328;
static lv_obj_t *face_70_2_dial_8_59328;
static lv_obj_t *face_70_2_dial_9_59328;
static lv_obj_t *face_70_2_dial_10_59328;
static lv_obj_t *face_70_2_dial_11_59328;
static lv_obj_t *face_70_2_dial_12_59328;
static lv_obj_t *face_70_2_dial_13_60900;
static lv_obj_t *face_70_2_dial_29_90967;
static lv_obj_t *face_70_2_dial_45_130547;

ZSW_LV_IMG_DECLARE(face_70_2_dial_0_1224_0);
ZSW_LV_IMG_DECLARE(face_70_2_dial_1_125929_0);
ZSW_LV_IMG_DECLARE(face_70_2_dial_1_125929_1);
ZSW_LV_IMG_DECLARE(face_70_2_dial_1_125929_2);
ZSW_LV_IMG_DECLARE(face_70_2_dial_1_125929_3);
ZSW_LV_IMG_DECLARE(face_70_2_dial_1_125929_4);
ZSW_LV_IMG_DECLARE(face_70_2_dial_1_125929_5);
ZSW_LV_IMG_DECLARE(face_70_2_dial_1_125929_6);
ZSW_LV_IMG_DECLARE(face_70_2_dial_1_125929_7);
ZSW_LV_IMG_DECLARE(face_70_2_dial_1_125929_8);
ZSW_LV_IMG_DECLARE(face_70_2_dial_1_125929_9);
ZSW_LV_IMG_DECLARE(face_70_2_dial_5_59328_0);
ZSW_LV_IMG_DECLARE(face_70_2_dial_5_59328_1);
ZSW_LV_IMG_DECLARE(face_70_2_dial_5_59328_2);
ZSW_LV_IMG_DECLARE(face_70_2_dial_5_59328_3);
ZSW_LV_IMG_DECLARE(face_70_2_dial_5_59328_4);
ZSW_LV_IMG_DECLARE(face_70_2_dial_5_59328_5);
ZSW_LV_IMG_DECLARE(face_70_2_dial_5_59328_6);
ZSW_LV_IMG_DECLARE(face_70_2_dial_5_59328_7);
ZSW_LV_IMG_DECLARE(face_70_2_dial_5_59328_8);
ZSW_LV_IMG_DECLARE(face_70_2_dial_5_59328_9);
ZSW_LV_IMG_DECLARE(face_70_2_dial_13_60900_0);
ZSW_LV_IMG_DECLARE(face_70_2_dial_29_90967_0);
ZSW_LV_IMG_DECLARE(face_70_2_dial_45_130547_0);
ZSW_LV_IMG_DECLARE(face_70_2_dial_preview_0);

#if CONFIG_LV_COLOR_DEPTH_16 != 1
#error "CONFIG_LV_COLOR_DEPTH_16 should be 16 bit for watchfaces"
#endif
#if CONFIG_LV_COLOR_16_SWAP != 1
#error "CONFIG_LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif

const void *face_70_2_dial_1_125929_group[] = {
    ZSW_LV_IMG_USE(face_70_2_dial_1_125929_0),
    ZSW_LV_IMG_USE(face_70_2_dial_1_125929_1),
    ZSW_LV_IMG_USE(face_70_2_dial_1_125929_2),
    ZSW_LV_IMG_USE(face_70_2_dial_1_125929_3),
    ZSW_LV_IMG_USE(face_70_2_dial_1_125929_4),
    ZSW_LV_IMG_USE(face_70_2_dial_1_125929_5),
    ZSW_LV_IMG_USE(face_70_2_dial_1_125929_6),
    ZSW_LV_IMG_USE(face_70_2_dial_1_125929_7),
    ZSW_LV_IMG_USE(face_70_2_dial_1_125929_8),
    ZSW_LV_IMG_USE(face_70_2_dial_1_125929_9),
};
const void *face_70_2_dial_5_59328_group[] = {
    ZSW_LV_IMG_USE(face_70_2_dial_5_59328_0),
    ZSW_LV_IMG_USE(face_70_2_dial_5_59328_1),
    ZSW_LV_IMG_USE(face_70_2_dial_5_59328_2),
    ZSW_LV_IMG_USE(face_70_2_dial_5_59328_3),
    ZSW_LV_IMG_USE(face_70_2_dial_5_59328_4),
    ZSW_LV_IMG_USE(face_70_2_dial_5_59328_5),
    ZSW_LV_IMG_USE(face_70_2_dial_5_59328_6),
    ZSW_LV_IMG_USE(face_70_2_dial_5_59328_7),
    ZSW_LV_IMG_USE(face_70_2_dial_5_59328_8),
    ZSW_LV_IMG_USE(face_70_2_dial_5_59328_9),
};

static int32_t getPlaceValue(int32_t num, int32_t place)
{
    int32_t divisor = 1;
    for (uint32_t i = 1; i < place; i++) {
        divisor *= 10;
    }
    return (num / divisor) % 10;
}

static int32_t setPlaceValue(int32_t num, int32_t place, int32_t newValue)
{
    int32_t divisor = 1;
    for (uint32_t i = 1; i < place; i++) {
        divisor *= 10;
    }
    return num - ((num / divisor) % 10 * divisor) + (newValue * divisor);
}

static void watchface_70_2_dial_remove(void)
{
    if (!face_70_2_dial) {
        return;
    }

    lv_obj_del(face_70_2_dial);
    face_70_2_dial = NULL;
}

static void watchface_70_2_dial_invalidate_cached(void)
{
    last_date = -1;
    last_day = -1;
    last_month = -1;
    last_year = -1;
    last_weekday = -1;
    last_hour = -1;
    last_minute = -1;
    last_steps = -1;
    last_distance = -1;
    last_kcal = -1;
}

static const void *watchface_70_2_dial_get_preview_img(void)
{
    return ZSW_LV_IMG_USE(face_70_2_dial_preview_0);
}

static void watchface_70_2_dial_set_datetime(int day_of_week, int date, int day, int month, int year, int weekday,
                                             int hour,
                                             int minute, int second, uint32_t usec, bool am, bool mode)
{
    if (!face_70_2_dial) {
        return;
    }

    if (getPlaceValue(last_hour, 1) != getPlaceValue(hour, 1)) {
        last_hour = setPlaceValue(last_hour, 1, getPlaceValue(hour, 1));
        lv_img_set_src(face_70_2_dial_1_125929, face_70_2_dial_1_125929_group[(hour / 1) % 10]);
    }

    if (getPlaceValue(last_hour, 2) != getPlaceValue(hour, 2)) {
        last_hour = setPlaceValue(last_hour, 2, getPlaceValue(hour, 2));
        lv_img_set_src(face_70_2_dial_2_125929, face_70_2_dial_1_125929_group[(hour / 10) % 10]);
    }

    if (getPlaceValue(last_minute, 1) != getPlaceValue(minute, 1)) {
        last_minute = setPlaceValue(last_minute, 1, getPlaceValue(minute, 1));
        lv_img_set_src(face_70_2_dial_3_125929, face_70_2_dial_1_125929_group[(minute / 1) % 10]);
    }

    if (getPlaceValue(last_minute, 2) != getPlaceValue(minute, 2)) {
        last_minute = setPlaceValue(last_minute, 2, getPlaceValue(minute, 2));
        lv_img_set_src(face_70_2_dial_4_125929, face_70_2_dial_1_125929_group[(minute / 10) % 10]);
    }
    lv_img_set_angle(face_70_2_dial_13_60900, hour * 300 + (minute * 5));
    lv_img_set_angle(face_70_2_dial_29_90967, minute * 60);
    lv_img_set_angle(face_70_2_dial_45_130547, second * 60);

}

static void watchface_70_2_dial_set_step(int32_t steps, int32_t distance, int32_t kcal)
{
    if (!face_70_2_dial) {
        return;
    }

    if (getPlaceValue(last_steps, 1) != getPlaceValue(steps, 1)) {
        last_steps = setPlaceValue(last_steps, 1, getPlaceValue(steps, 1));
        lv_img_set_src(face_70_2_dial_8_59328, face_70_2_dial_5_59328_group[(steps / 1) % 10]);
    }

    if (getPlaceValue(last_steps, 2) != getPlaceValue(steps, 2)) {
        last_steps = setPlaceValue(last_steps, 2, getPlaceValue(steps, 2));
        lv_img_set_src(face_70_2_dial_9_59328, face_70_2_dial_5_59328_group[(steps / 10) % 10]);
    }

    if (getPlaceValue(last_steps, 3) != getPlaceValue(steps, 3)) {
        last_steps = setPlaceValue(last_steps, 3, getPlaceValue(steps, 3));
        lv_img_set_src(face_70_2_dial_10_59328, face_70_2_dial_5_59328_group[(steps / 100) % 10]);
    }

    if (getPlaceValue(last_steps, 4) != getPlaceValue(steps, 4)) {
        last_steps = setPlaceValue(last_steps, 4, getPlaceValue(steps, 4));
        lv_img_set_src(face_70_2_dial_11_59328, face_70_2_dial_5_59328_group[(steps / 1000) % 10]);
    }

    if (getPlaceValue(last_steps, 5) != getPlaceValue(steps, 5)) {
        last_steps = setPlaceValue(last_steps, 5, getPlaceValue(steps, 5));
        lv_img_set_src(face_70_2_dial_12_59328, face_70_2_dial_5_59328_group[(steps / 10000) % 10]);
    }

}

static void watchface_70_2_dial_set_hrm(int32_t bpm, int32_t oxygen)
{
    if (!face_70_2_dial) {
        return;
    }

    lv_img_set_src(face_70_2_dial_5_59328, face_70_2_dial_5_59328_group[(bpm / 1) % 10]);
    lv_img_set_src(face_70_2_dial_6_59328, face_70_2_dial_5_59328_group[(bpm / 10) % 10]);
    lv_img_set_src(face_70_2_dial_7_59328, face_70_2_dial_5_59328_group[(bpm / 100) % 10]);

}

static void watchface_70_2_dial_set_weather(int8_t temp, int icon)
{
    if (!face_70_2_dial) {
        return;
    }

}

static void watchface_70_2_dial_set_ble_connected(bool connected)
{
    if (!face_70_2_dial) {
        return;
    }

}

static void watchface_70_2_dial_set_battery_percent(int32_t percent, int32_t battery)
{
    if (!face_70_2_dial) {
        return;
    }

}

static void watchface_70_2_dial_set_num_notifcations(int32_t number)
{
    if (!face_70_2_dial) {
        return;
    }

}

static void watchface_70_2_dial_set_watch_env_sensors(int temperature, int humidity, int pressure, float iaq, float co2)
{
    if (!face_70_2_dial) {
        return;
    }

}

void watchface_70_2_dial_show(lv_obj_t *parent, watchface_app_evt_listener evt_cb, zsw_settings_watchface_t *settings)
{
    ui_70_2_dial_evt_cb = evt_cb;

    lv_obj_clear_flag(parent, LV_OBJ_FLAG_SCROLLABLE);
    face_70_2_dial = lv_obj_create(parent);
    watchface_70_2_dial_invalidate_cached();

    lv_obj_clear_flag(face_70_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scrollbar_mode(face_70_2_dial, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_opa(face_70_2_dial, LV_OPA_TRANSP, LV_PART_MAIN);

    lv_obj_set_style_border_width(face_70_2_dial, 0, LV_PART_MAIN);
    lv_obj_set_size(face_70_2_dial, 240, 240);
    lv_obj_clear_flag(face_70_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_70_2_dial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_70_2_dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_70_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_70_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_70_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_70_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_70_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    face_70_2_dial_0_1224 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_0_1224, ZSW_LV_IMG_USE(face_70_2_dial_0_1224_0));
    lv_obj_set_width(face_70_2_dial_0_1224, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_0_1224, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_0_1224, 0);
    lv_obj_set_y(face_70_2_dial_0_1224, 0);
    lv_obj_add_flag(face_70_2_dial_0_1224, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_0_1224, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_1_125929 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_1_125929, ZSW_LV_IMG_USE(face_70_2_dial_1_125929_0));
    lv_obj_set_width(face_70_2_dial_1_125929, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_1_125929, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_1_125929, 205);
    lv_obj_set_y(face_70_2_dial_1_125929, 89);
    lv_obj_add_flag(face_70_2_dial_1_125929, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_1_125929, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_2_125929 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_2_125929, ZSW_LV_IMG_USE(face_70_2_dial_1_125929_0));
    lv_obj_set_width(face_70_2_dial_2_125929, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_2_125929, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_2_125929, 182);
    lv_obj_set_y(face_70_2_dial_2_125929, 89);
    lv_obj_add_flag(face_70_2_dial_2_125929, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_2_125929, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_3_125929 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_3_125929, ZSW_LV_IMG_USE(face_70_2_dial_1_125929_0));
    lv_obj_set_width(face_70_2_dial_3_125929, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_3_125929, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_3_125929, 205);
    lv_obj_set_y(face_70_2_dial_3_125929, 125);
    lv_obj_add_flag(face_70_2_dial_3_125929, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_3_125929, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_4_125929 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_4_125929, ZSW_LV_IMG_USE(face_70_2_dial_1_125929_0));
    lv_obj_set_width(face_70_2_dial_4_125929, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_4_125929, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_4_125929, 182);
    lv_obj_set_y(face_70_2_dial_4_125929, 125);
    lv_obj_add_flag(face_70_2_dial_4_125929, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_4_125929, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_5_59328 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_5_59328, ZSW_LV_IMG_USE(face_70_2_dial_5_59328_0));
    lv_obj_set_width(face_70_2_dial_5_59328, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_5_59328, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_5_59328, 43);
    lv_obj_set_y(face_70_2_dial_5_59328, 107);
    lv_obj_add_flag(face_70_2_dial_5_59328, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_5_59328, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_6_59328 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_6_59328, ZSW_LV_IMG_USE(face_70_2_dial_5_59328_0));
    lv_obj_set_width(face_70_2_dial_6_59328, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_6_59328, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_6_59328, 32);
    lv_obj_set_y(face_70_2_dial_6_59328, 107);
    lv_obj_add_flag(face_70_2_dial_6_59328, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_6_59328, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_7_59328 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_7_59328, ZSW_LV_IMG_USE(face_70_2_dial_5_59328_0));
    lv_obj_set_width(face_70_2_dial_7_59328, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_7_59328, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_7_59328, 21);
    lv_obj_set_y(face_70_2_dial_7_59328, 107);
    lv_obj_add_flag(face_70_2_dial_7_59328, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_7_59328, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_8_59328 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_8_59328, ZSW_LV_IMG_USE(face_70_2_dial_5_59328_0));
    lv_obj_set_width(face_70_2_dial_8_59328, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_8_59328, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_8_59328, 55);
    lv_obj_set_y(face_70_2_dial_8_59328, 128);
    lv_obj_add_flag(face_70_2_dial_8_59328, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_8_59328, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_9_59328 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_9_59328, ZSW_LV_IMG_USE(face_70_2_dial_5_59328_0));
    lv_obj_set_width(face_70_2_dial_9_59328, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_9_59328, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_9_59328, 44);
    lv_obj_set_y(face_70_2_dial_9_59328, 128);
    lv_obj_add_flag(face_70_2_dial_9_59328, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_9_59328, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_10_59328 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_10_59328, ZSW_LV_IMG_USE(face_70_2_dial_5_59328_0));
    lv_obj_set_width(face_70_2_dial_10_59328, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_10_59328, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_10_59328, 33);
    lv_obj_set_y(face_70_2_dial_10_59328, 128);
    lv_obj_add_flag(face_70_2_dial_10_59328, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_10_59328, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_11_59328 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_11_59328, ZSW_LV_IMG_USE(face_70_2_dial_5_59328_0));
    lv_obj_set_width(face_70_2_dial_11_59328, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_11_59328, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_11_59328, 22);
    lv_obj_set_y(face_70_2_dial_11_59328, 128);
    lv_obj_add_flag(face_70_2_dial_11_59328, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_11_59328, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_12_59328 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_12_59328, ZSW_LV_IMG_USE(face_70_2_dial_5_59328_0));
    lv_obj_set_width(face_70_2_dial_12_59328, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_12_59328, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_12_59328, 11);
    lv_obj_set_y(face_70_2_dial_12_59328, 128);
    lv_obj_add_flag(face_70_2_dial_12_59328, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_12_59328, LV_OBJ_FLAG_SCROLLABLE);

    face_70_2_dial_13_60900 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_13_60900, ZSW_LV_IMG_USE(face_70_2_dial_13_60900_0));
    lv_obj_set_width(face_70_2_dial_13_60900, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_13_60900, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_13_60900, 110);
    lv_obj_set_y(face_70_2_dial_13_60900, 9);
    lv_obj_add_flag(face_70_2_dial_13_60900, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_13_60900, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(face_70_2_dial_13_60900, 10, 51);

    face_70_2_dial_29_90967 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_29_90967, ZSW_LV_IMG_USE(face_70_2_dial_29_90967_0));
    lv_obj_set_width(face_70_2_dial_29_90967, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_29_90967, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_29_90967, 111);
    lv_obj_set_y(face_70_2_dial_29_90967, 121);
    lv_obj_add_flag(face_70_2_dial_29_90967, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_29_90967, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(face_70_2_dial_29_90967, 9, 59);

    face_70_2_dial_45_130547 = lv_img_create(face_70_2_dial);
    lv_img_set_src(face_70_2_dial_45_130547, ZSW_LV_IMG_USE(face_70_2_dial_45_130547_0));
    lv_obj_set_width(face_70_2_dial_45_130547, LV_SIZE_CONTENT);
    lv_obj_set_height(face_70_2_dial_45_130547, LV_SIZE_CONTENT);
    lv_obj_set_x(face_70_2_dial_45_130547, 118);
    lv_obj_set_y(face_70_2_dial_45_130547, 112);
    lv_obj_add_flag(face_70_2_dial_45_130547, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_70_2_dial_45_130547, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(face_70_2_dial_45_130547, 2, 8);

}

static watchface_ui_api_t ui_api = {
    .show = watchface_70_2_dial_show,
    .remove = watchface_70_2_dial_remove,
    .set_battery_percent = watchface_70_2_dial_set_battery_percent,
    .set_hrm = watchface_70_2_dial_set_hrm,
    .set_step = watchface_70_2_dial_set_step,
    .set_ble_connected = watchface_70_2_dial_set_ble_connected,
    .set_num_notifcations = watchface_70_2_dial_set_num_notifcations,
    .set_weather = watchface_70_2_dial_set_weather,
    .set_datetime = watchface_70_2_dial_set_datetime,
    .set_watch_env_sensors = watchface_70_2_dial_set_watch_env_sensors,
    .ui_invalidate_cached = watchface_70_2_dial_invalidate_cached,
    .get_preview_img = watchface_70_2_dial_get_preview_img,
    .name = "Yin-yang",
};

static int watchface_70_2_dial_init(void)
{
    watchface_app_register_ui(&ui_api);

    return 0;
}

SYS_INIT(watchface_70_2_dial_init, APPLICATION, WATCHFACE_UI_INIT_PRIO);
