
// File generated by bin2lvgl
// developed by fbiego.
// https://github.com/fbiego
// modified by Daniel Kampert.
// https://github.com/kampi
// Watchface: 80_2_dial

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_80_2_dial_22_89272_data_0[] = {
    0xEA,0x4A,0xEA,0x4A,0xFA,0xC7,0xFA,0xC7,0x75,0x9E,0x79,0xB7,0x03,0x19,0x85,0x21,
    0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
}; // LVGL_9 compatible

const lv_img_dsc_t face_80_2_dial_22_89272_0 = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w = 2,
    .header.h = 4,
    .data_size = sizeof(face_80_2_dial_22_89272_data_0),
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .data = face_80_2_dial_22_89272_data_0};
