
// File generated by bin2lvgl
// developed by fbiego.
// https://github.com/fbiego
// modified by Daniel Kampert.
// https://github.com/kampi
// Watchface: goog

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_goog_32_65535_data_0[] = {
    0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
    0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
}; // LVGL_9 compatible

const lv_img_dsc_t face_goog_32_65535_0 = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w = 6,
    .header.h = 1,
    .data_size = sizeof(face_goog_32_65535_data_0),
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .data = face_goog_32_65535_data_0};
