
// File generated by bin2lvgl
// developed by fbiego.
// https://github.com/fbiego
// modified by Daniel Kampert.
// https://github.com/kampi
// Watchface: 84_2_dial

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_84_2_dial_6_231174_data_0[] = {
    0xAA,0x52,0xBA,0xD6,0xBA,0xD6,0xBA,0xD6,0xBA,0xD6,0xBA,0xD6,0x2C,0x63,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
    0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
}; // LVGL_9 compatible

const lv_img_dsc_t face_84_2_dial_6_231174_0 = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w = 6,
    .header.h = 2,
    .data_size = sizeof(face_84_2_dial_6_231174_data_0),
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .data = face_84_2_dial_6_231174_data_0};
