
// File generated by bin2lvgl
// developed by Daniel Kampert. 
// https://github.com/kampi
// Watchface: 107_2_dial

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_107_2_dial_dial_img_1_58372_data_0[] = {
	0x73,0xAE,0xFF,0xBD,0xD7,0xFF,0x63,0x2C,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0x9C,0xD3,0xFF,0xFF,0xFF,0xFF,0x73,0xAE,0xFF,
    };
        

const lv_img_dsc_t face_107_2_dial_dial_img_1_58372_0 = {
    .header.always_zero = 0,
    .header.w = 3,
    .header.h = 3,
    .data_size = sizeof(face_107_2_dial_dial_img_1_58372_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_107_2_dial_dial_img_1_58372_data_0};
    