
// File generated by bin2lvgl
// developed by fbiego.
// https://github.com/fbiego
// modified by Daniel Kampert.
// https://github.com/kampi
// Watchface: 73_2_dial

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_73_2_dial_7_59924_data_0[] = {
	0x18,0x81,0xFF,0x69,0xC4,0xFF,0x69,0xC4,0xFF,0x69,0xC4,0xFF,0x39,0x02,0xFF,0x39,0x02,0xFF,0xEB,0xE9,0xFF,0xEB,0xE9,0xFF,0xEB,0xE9,0xFF,0x69,0xC4,0xFF,
    };

const lv_img_dsc_t face_73_2_dial_7_59924_0 = {
    .header.always_zero = 0,
    .header.w = 5,
    .header.h = 2,
    .data_size = sizeof(face_73_2_dial_7_59924_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_73_2_dial_7_59924_data_0};
