
// File generated by bin2lvgl
// developed by fbiego.
// https://github.com/fbiego
// modified by Daniel Kampert.
// https://github.com/kampi
// Watchface: 107_2_dial

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_107_2_dial_1_58372_data_0[] = {
    0xAE,0x73,0xD7,0xBD,0x2C,0x63,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xD3,0x9C,0xFF,0xFF,0xAE,0x73,
    0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
}; // LVGL_9 compatible

const lv_img_dsc_t face_107_2_dial_1_58372_0 = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w = 3,
    .header.h = 3,
    .data_size = sizeof(face_107_2_dial_1_58372_data_0),
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .data = face_107_2_dial_1_58372_data_0};
