manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: sdk
      url-base: https://github.com/nrfconnect
    - name: bosch
      url-base: https://github.com/boschsensortec

  group-filter: [-bsec2]

  projects:
    - name: sdk-nrf
      remote: sdk
      revision: v3.0.2
      path: nrf
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_ti
          - loramac-node
          - net-tools
          - edtt
          - trusted-firmware-m
          - sof
      clone-depth: 1

    - name: bsec2
      repo-path: Bosch-BSEC2-Library
      remote: bosch
      path: app/src/ext_drivers/BSEC2
      groups:
        - bsec2
      
  self:
    west-commands: scripts/west-commands.yml