manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: sdk
      url-base: https://github.com/nrfconnect
    - name: bosch
      url-base: https://github.com/boschsensortec

  group-filter: [-bsec2]

  projects:
    - name: sdk-nrf
      remote: sdk
      revision: v3.1.0
      path: nrf
      import:
        name-blocklist:
          - azure-sdk-for-c
          - bsim
          - canopennode
          - chre
          - ci-tools
          - edtt
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_ti
          - hal_xtensa
          - liblc3
          - nrf_wifi
          - hostap
          - loramac-node
          - mipi-sys-t
          - matter
          - memfault-firmware-sdk
          - nanopb
          - net-tools
          - nrf_hw_models
          - openthread
          - percepio
          - psa-arch-tests
          - qcbor
          - tf-m-tests
          - sof
          - trusted-firmware-m
          - zscilib
          - wfa-qt-control-app
      clone-depth: 1

    - name: bsec2
      repo-path: Bosch-BSEC2-Library
      remote: bosch
      path: app/src/ext_drivers/BSEC2
      groups:
        - bsec2
      
  self:
    west-commands: scripts/west-commands.yml