
// File generated by bin2lvgl
// developed by fbiego.
// https://github.com/fbiego
// modified by Daniel Kampert.
// https://github.com/kampi
// Watchface: 80_2_dial

#include <lvgl.h>

#include <zephyr/logging/log.h>

#include "ui/zsw_ui.h"
#include "applications/watchface/watchface_app.h"

LOG_MODULE_REGISTER(watchface_80_2_dial, LOG_LEVEL_WRN);

static lv_obj_t *face_80_2_dial;
static lv_obj_t *face_80_2_dial = NULL;
static watchface_app_evt_listener ui_80_2_dial_evt_cb;

static int last_date = -1;
static int last_day = -1;
static int last_month = -1;
static int last_year = -1;
static int last_weekday = -1;
static int last_hour = -1;
static int last_minute = -1;

static int last_steps = -1;
static int last_distance = -1;
static int last_kcal = -1;

static lv_obj_t *face_80_2_dial_0_2768;
static lv_obj_t *face_80_2_dial_1_24923;
static lv_obj_t *face_80_2_dial_2_85197;
static lv_obj_t *face_80_2_dial_3_85197;
static lv_obj_t *face_80_2_dial_4_85197;
static lv_obj_t *face_80_2_dial_5_85197;
static lv_obj_t *face_80_2_dial_6_85197;
static lv_obj_t *face_80_2_dial_7_85197;
static lv_obj_t *face_80_2_dial_8_85197;
static lv_obj_t *face_80_2_dial_9_85197;
static lv_obj_t *face_80_2_dial_10_85197;
static lv_obj_t *face_80_2_dial_12_94522;
static lv_obj_t *face_80_2_dial_14_89131;
static lv_obj_t *face_80_2_dial_16_89866;
static lv_obj_t *face_80_2_dial_17_85197;
static lv_obj_t *face_80_2_dial_18_85197;
static lv_obj_t *face_80_2_dial_19_85197;
static lv_obj_t *face_80_2_dial_20_85197;
static lv_obj_t *face_80_2_dial_21_89292;
static lv_obj_t *face_80_2_dial_22_89272;
static lv_obj_t *face_80_2_dial_23_85197;
static lv_obj_t *face_80_2_dial_24_85197;
static lv_obj_t *face_80_2_dial_25_85197;
static lv_obj_t *face_80_2_dial_26_88651;
static lv_obj_t *face_80_2_dial_27_85197;
static lv_obj_t *face_80_2_dial_28_85197;
static lv_obj_t *face_80_2_dial_29_85197;
static lv_obj_t *face_80_2_dial_31_2056;
static lv_obj_t *face_80_2_dial_33_92190;
static lv_obj_t *face_80_2_dial_35_113802;
static lv_obj_t *face_80_2_dial_36_96224;
static lv_obj_t *face_80_2_dial_37_96394;
static lv_obj_t *face_80_2_dial_38_96394;
static lv_obj_t *face_80_2_dial_39_96394;
static lv_obj_t *face_80_2_dial_40_96394;
static lv_obj_t *face_80_2_dial_41_86829;
static lv_obj_t *face_80_2_dial_42_86829;
static lv_obj_t *face_80_2_dial_43_86861;
static lv_obj_t *face_80_2_dial_44_86861;
static lv_obj_t *face_80_2_dial_45_86861;
static lv_obj_t *face_80_2_dial_46_86861;
static lv_obj_t *face_80_2_dial_47_86861;
static lv_obj_t *face_80_2_dial_48_86861;
static lv_obj_t *face_80_2_dial_49_86861;
static lv_obj_t *face_80_2_dial_50_86861;
static lv_obj_t *face_80_2_dial_53_86861;
static lv_obj_t *face_80_2_dial_54_86861;
static lv_obj_t *face_80_2_dial_55_106772;
static lv_obj_t *face_80_2_dial_56_25742;
static lv_obj_t *face_80_2_dial_58_84569;

ZSW_LV_IMG_DECLARE(face_80_2_dial_0_2768_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_1_24923_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_1_24923_1);
ZSW_LV_IMG_DECLARE(face_80_2_dial_1_24923_2);
ZSW_LV_IMG_DECLARE(face_80_2_dial_1_24923_3);
ZSW_LV_IMG_DECLARE(face_80_2_dial_1_24923_4);
ZSW_LV_IMG_DECLARE(face_80_2_dial_1_24923_5);
ZSW_LV_IMG_DECLARE(face_80_2_dial_1_24923_6);
ZSW_LV_IMG_DECLARE(face_80_2_dial_2_85197_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_2_85197_1);
ZSW_LV_IMG_DECLARE(face_80_2_dial_2_85197_2);
ZSW_LV_IMG_DECLARE(face_80_2_dial_2_85197_3);
ZSW_LV_IMG_DECLARE(face_80_2_dial_2_85197_4);
ZSW_LV_IMG_DECLARE(face_80_2_dial_2_85197_5);
ZSW_LV_IMG_DECLARE(face_80_2_dial_2_85197_6);
ZSW_LV_IMG_DECLARE(face_80_2_dial_2_85197_7);
ZSW_LV_IMG_DECLARE(face_80_2_dial_2_85197_8);
ZSW_LV_IMG_DECLARE(face_80_2_dial_2_85197_9);
ZSW_LV_IMG_DECLARE(face_80_2_dial_11_94008_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_12_94522_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_13_88917_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_14_89131_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_15_89638_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_16_89866_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_21_89292_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_22_89272_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_26_88651_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_30_1344_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_30_1344_1);
ZSW_LV_IMG_DECLARE(face_80_2_dial_31_2056_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_31_2056_1);
ZSW_LV_IMG_DECLARE(face_80_2_dial_32_91516_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_32_91516_1);
ZSW_LV_IMG_DECLARE(face_80_2_dial_33_92190_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_33_92190_1);
ZSW_LV_IMG_DECLARE(face_80_2_dial_34_106838_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_34_106838_1);
ZSW_LV_IMG_DECLARE(face_80_2_dial_34_106838_2);
ZSW_LV_IMG_DECLARE(face_80_2_dial_34_106838_3);
ZSW_LV_IMG_DECLARE(face_80_2_dial_34_106838_4);
ZSW_LV_IMG_DECLARE(face_80_2_dial_34_106838_5);
ZSW_LV_IMG_DECLARE(face_80_2_dial_34_106838_6);
ZSW_LV_IMG_DECLARE(face_80_2_dial_35_113802_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_35_113802_1);
ZSW_LV_IMG_DECLARE(face_80_2_dial_35_113802_2);
ZSW_LV_IMG_DECLARE(face_80_2_dial_35_113802_3);
ZSW_LV_IMG_DECLARE(face_80_2_dial_35_113802_4);
ZSW_LV_IMG_DECLARE(face_80_2_dial_35_113802_5);
ZSW_LV_IMG_DECLARE(face_80_2_dial_35_113802_6);
ZSW_LV_IMG_DECLARE(face_80_2_dial_36_96224_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_37_96394_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_37_96394_1);
ZSW_LV_IMG_DECLARE(face_80_2_dial_37_96394_2);
ZSW_LV_IMG_DECLARE(face_80_2_dial_37_96394_3);
ZSW_LV_IMG_DECLARE(face_80_2_dial_37_96394_4);
ZSW_LV_IMG_DECLARE(face_80_2_dial_37_96394_5);
ZSW_LV_IMG_DECLARE(face_80_2_dial_37_96394_6);
ZSW_LV_IMG_DECLARE(face_80_2_dial_37_96394_7);
ZSW_LV_IMG_DECLARE(face_80_2_dial_37_96394_8);
ZSW_LV_IMG_DECLARE(face_80_2_dial_37_96394_9);
ZSW_LV_IMG_DECLARE(face_80_2_dial_41_86829_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_43_86861_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_43_86861_1);
ZSW_LV_IMG_DECLARE(face_80_2_dial_43_86861_2);
ZSW_LV_IMG_DECLARE(face_80_2_dial_43_86861_3);
ZSW_LV_IMG_DECLARE(face_80_2_dial_43_86861_4);
ZSW_LV_IMG_DECLARE(face_80_2_dial_43_86861_5);
ZSW_LV_IMG_DECLARE(face_80_2_dial_43_86861_6);
ZSW_LV_IMG_DECLARE(face_80_2_dial_43_86861_7);
ZSW_LV_IMG_DECLARE(face_80_2_dial_43_86861_8);
ZSW_LV_IMG_DECLARE(face_80_2_dial_43_86861_9);
ZSW_LV_IMG_DECLARE(face_80_2_dial_51_25742_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_55_106772_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_58_84569_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_59_95772_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_60_95193_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_61_92864_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_62_90896_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_63_93384_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_64_119072_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_65_88153_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_66_90093_0);
ZSW_LV_IMG_DECLARE(face_80_2_dial_preview_0);

#if CONFIG_LV_COLOR_DEPTH_16 != 1
#error "CONFIG_LV_COLOR_DEPTH_16 should be 16 bit for watchfaces"
#endif
#if CONFIG_LV_COLOR_16_SWAP != 1
#error "CONFIG_LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif

const void *face_80_2_dial_1_24923_group[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_1_24923_0),
    ZSW_LV_IMG_USE(face_80_2_dial_1_24923_1),
    ZSW_LV_IMG_USE(face_80_2_dial_1_24923_2),
    ZSW_LV_IMG_USE(face_80_2_dial_1_24923_3),
    ZSW_LV_IMG_USE(face_80_2_dial_1_24923_4),
    ZSW_LV_IMG_USE(face_80_2_dial_1_24923_5),
    ZSW_LV_IMG_USE(face_80_2_dial_1_24923_6),
};
const void *face_80_2_dial_2_85197_group[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0),
    ZSW_LV_IMG_USE(face_80_2_dial_2_85197_1),
    ZSW_LV_IMG_USE(face_80_2_dial_2_85197_2),
    ZSW_LV_IMG_USE(face_80_2_dial_2_85197_3),
    ZSW_LV_IMG_USE(face_80_2_dial_2_85197_4),
    ZSW_LV_IMG_USE(face_80_2_dial_2_85197_5),
    ZSW_LV_IMG_USE(face_80_2_dial_2_85197_6),
    ZSW_LV_IMG_USE(face_80_2_dial_2_85197_7),
    ZSW_LV_IMG_USE(face_80_2_dial_2_85197_8),
    ZSW_LV_IMG_USE(face_80_2_dial_2_85197_9),
};
const void *face_80_2_dial_30_1344_group[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_30_1344_0),
    ZSW_LV_IMG_USE(face_80_2_dial_30_1344_1),
};
const void *face_80_2_dial_31_2056_group[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_31_2056_0),
    ZSW_LV_IMG_USE(face_80_2_dial_31_2056_1),
};
const void *face_80_2_dial_32_91516_group[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_32_91516_0),
    ZSW_LV_IMG_USE(face_80_2_dial_32_91516_1),
};
const void *face_80_2_dial_33_92190_group[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_33_92190_0),
    ZSW_LV_IMG_USE(face_80_2_dial_33_92190_1),
};
const void *face_80_2_dial_34_106838_group[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_34_106838_0),
    ZSW_LV_IMG_USE(face_80_2_dial_34_106838_1),
    ZSW_LV_IMG_USE(face_80_2_dial_34_106838_2),
    ZSW_LV_IMG_USE(face_80_2_dial_34_106838_3),
    ZSW_LV_IMG_USE(face_80_2_dial_34_106838_4),
    ZSW_LV_IMG_USE(face_80_2_dial_34_106838_5),
    ZSW_LV_IMG_USE(face_80_2_dial_34_106838_6),
};
const void *face_80_2_dial_35_113802_group[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_35_113802_0),
    ZSW_LV_IMG_USE(face_80_2_dial_35_113802_1),
    ZSW_LV_IMG_USE(face_80_2_dial_35_113802_2),
    ZSW_LV_IMG_USE(face_80_2_dial_35_113802_3),
    ZSW_LV_IMG_USE(face_80_2_dial_35_113802_4),
    ZSW_LV_IMG_USE(face_80_2_dial_35_113802_5),
    ZSW_LV_IMG_USE(face_80_2_dial_35_113802_6),
};
const void *face_80_2_dial_37_96394_group[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_37_96394_0),
    ZSW_LV_IMG_USE(face_80_2_dial_37_96394_1),
    ZSW_LV_IMG_USE(face_80_2_dial_37_96394_2),
    ZSW_LV_IMG_USE(face_80_2_dial_37_96394_3),
    ZSW_LV_IMG_USE(face_80_2_dial_37_96394_4),
    ZSW_LV_IMG_USE(face_80_2_dial_37_96394_5),
    ZSW_LV_IMG_USE(face_80_2_dial_37_96394_6),
    ZSW_LV_IMG_USE(face_80_2_dial_37_96394_7),
    ZSW_LV_IMG_USE(face_80_2_dial_37_96394_8),
    ZSW_LV_IMG_USE(face_80_2_dial_37_96394_9),
};
const void *face_80_2_dial_43_86861_group[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0),
    ZSW_LV_IMG_USE(face_80_2_dial_43_86861_1),
    ZSW_LV_IMG_USE(face_80_2_dial_43_86861_2),
    ZSW_LV_IMG_USE(face_80_2_dial_43_86861_3),
    ZSW_LV_IMG_USE(face_80_2_dial_43_86861_4),
    ZSW_LV_IMG_USE(face_80_2_dial_43_86861_5),
    ZSW_LV_IMG_USE(face_80_2_dial_43_86861_6),
    ZSW_LV_IMG_USE(face_80_2_dial_43_86861_7),
    ZSW_LV_IMG_USE(face_80_2_dial_43_86861_8),
    ZSW_LV_IMG_USE(face_80_2_dial_43_86861_9),
};
const void *face_80_2_dial_weather[] = {
    ZSW_LV_IMG_USE(face_80_2_dial_58_84569_0),
    ZSW_LV_IMG_USE(face_80_2_dial_59_95772_0),
    ZSW_LV_IMG_USE(face_80_2_dial_60_95193_0),
    ZSW_LV_IMG_USE(face_80_2_dial_61_92864_0),
    ZSW_LV_IMG_USE(face_80_2_dial_62_90896_0),
    ZSW_LV_IMG_USE(face_80_2_dial_63_93384_0),
    ZSW_LV_IMG_USE(face_80_2_dial_64_119072_0),
    ZSW_LV_IMG_USE(face_80_2_dial_65_88153_0),
    ZSW_LV_IMG_USE(face_80_2_dial_66_90093_0),
};

static int32_t getPlaceValue(int32_t num, int32_t place)
{
    int32_t divisor = 1;
    for (uint32_t i = 1; i < place; i++) {
        divisor *= 10;
    }
    return (num / divisor) % 10;
}

static int32_t setPlaceValue(int32_t num, int32_t place, int32_t newValue)
{
    int32_t divisor = 1;
    for (uint32_t i = 1; i < place; i++) {
        divisor *= 10;
    }
    return num - ((num / divisor) % 10 * divisor) + (newValue * divisor);
}

static void watchface_80_2_dial_remove(void)
{
    if (!face_80_2_dial) {
        return;
    }

    lv_obj_del(face_80_2_dial);
    face_80_2_dial = NULL;
}

static void watchface_80_2_dial_invalidate_cached(void)
{
    last_date = -1;
    last_day = -1;
    last_month = -1;
    last_year = -1;
    last_weekday = -1;
    last_hour = -1;
    last_minute = -1;
    last_steps = -1;
    last_distance = -1;
    last_kcal = -1;
}

static const void *watchface_80_2_dial_get_preview_img(void)
{
    return ZSW_LV_IMG_USE(face_80_2_dial_preview_0);
}

static void watchface_80_2_dial_set_datetime(int day_of_week, int date, int day, int month, int year, int weekday,
                                             int hour,
                                             int minute, int second, uint32_t usec, bool am, bool mode)
{
    if (!face_80_2_dial) {
        return;
    }

    if (mode) {
        lv_obj_add_flag(face_80_2_dial_31_2056, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_clear_flag(face_80_2_dial_31_2056, LV_OBJ_FLAG_HIDDEN);
    }
    lv_img_set_src(face_80_2_dial_31_2056, face_80_2_dial_31_2056_group[(am ? 0 : 1) % 2]);
    if (mode) {
        lv_obj_add_flag(face_80_2_dial_33_92190, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_clear_flag(face_80_2_dial_33_92190, LV_OBJ_FLAG_HIDDEN);
    }
    lv_img_set_src(face_80_2_dial_33_92190, face_80_2_dial_33_92190_group[(am ? 0 : 1) % 2]);

    if (getPlaceValue(last_weekday, 1) != getPlaceValue(weekday, 1)) {
        last_weekday = setPlaceValue(last_weekday, 1, getPlaceValue(weekday, 1));
        lv_img_set_src(face_80_2_dial_35_113802, face_80_2_dial_35_113802_group[((weekday + 6) / 1) % 7]);
    }

    if (getPlaceValue(last_hour, 1) != getPlaceValue(hour, 1)) {
        last_hour = setPlaceValue(last_hour, 1, getPlaceValue(hour, 1));
        lv_img_set_src(face_80_2_dial_37_96394, face_80_2_dial_37_96394_group[(hour / 1) % 10]);
    }

    if (getPlaceValue(last_hour, 2) != getPlaceValue(hour, 2)) {
        last_hour = setPlaceValue(last_hour, 2, getPlaceValue(hour, 2));
        lv_img_set_src(face_80_2_dial_38_96394, face_80_2_dial_37_96394_group[(hour / 10) % 10]);
    }

    if (getPlaceValue(last_minute, 1) != getPlaceValue(minute, 1)) {
        last_minute = setPlaceValue(last_minute, 1, getPlaceValue(minute, 1));
        lv_img_set_src(face_80_2_dial_39_96394, face_80_2_dial_37_96394_group[(minute / 1) % 10]);
    }

    if (getPlaceValue(last_minute, 2) != getPlaceValue(minute, 2)) {
        last_minute = setPlaceValue(last_minute, 2, getPlaceValue(minute, 2));
        lv_img_set_src(face_80_2_dial_40_96394, face_80_2_dial_37_96394_group[(minute / 10) % 10]);
    }

    if (getPlaceValue(last_year, 1) != getPlaceValue(year, 1)) {
        last_year = setPlaceValue(last_year, 1, getPlaceValue(year, 1));
        lv_img_set_src(face_80_2_dial_43_86861, face_80_2_dial_43_86861_group[(year / 1) % 10]);
    }

    if (getPlaceValue(last_year, 2) != getPlaceValue(year, 2)) {
        last_year = setPlaceValue(last_year, 2, getPlaceValue(year, 2));
        lv_img_set_src(face_80_2_dial_44_86861, face_80_2_dial_43_86861_group[(year / 10) % 10]);
    }

    if (getPlaceValue(last_year, 3) != getPlaceValue(year, 3)) {
        last_year = setPlaceValue(last_year, 3, getPlaceValue(year, 3));
        lv_img_set_src(face_80_2_dial_45_86861, face_80_2_dial_43_86861_group[(year / 100) % 10]);
    }

    if (getPlaceValue(last_year, 4) != getPlaceValue(year, 4)) {
        last_year = setPlaceValue(last_year, 4, getPlaceValue(year, 4));
        lv_img_set_src(face_80_2_dial_46_86861, face_80_2_dial_43_86861_group[(year / 1000) % 10]);
    }

    if (getPlaceValue(last_month, 1) != getPlaceValue(month, 1)) {
        last_month = setPlaceValue(last_month, 1, getPlaceValue(month, 1));
        lv_img_set_src(face_80_2_dial_47_86861, face_80_2_dial_43_86861_group[(month / 1) % 10]);
    }

    if (getPlaceValue(last_month, 2) != getPlaceValue(month, 2)) {
        last_month = setPlaceValue(last_month, 2, getPlaceValue(month, 2));
        lv_img_set_src(face_80_2_dial_48_86861, face_80_2_dial_43_86861_group[(month / 10) % 10]);
    }

    if (getPlaceValue(last_day, 1) != getPlaceValue(day, 1)) {
        last_day = setPlaceValue(last_day, 1, getPlaceValue(day, 1));
        lv_img_set_src(face_80_2_dial_49_86861, face_80_2_dial_43_86861_group[(day / 1) % 10]);
    }

    if (getPlaceValue(last_day, 2) != getPlaceValue(day, 2)) {
        last_day = setPlaceValue(last_day, 2, getPlaceValue(day, 2));
        lv_img_set_src(face_80_2_dial_50_86861, face_80_2_dial_43_86861_group[(day / 10) % 10]);
    }

}

static void watchface_80_2_dial_set_step(int32_t steps, int32_t distance, int32_t kcal)
{
    if (!face_80_2_dial) {
        return;
    }

    if (getPlaceValue(last_steps, 1) != getPlaceValue(steps, 1)) {
        last_steps = setPlaceValue(last_steps, 1, getPlaceValue(steps, 1));
        lv_img_set_src(face_80_2_dial_2_85197, face_80_2_dial_2_85197_group[(steps / 1) % 10]);
    }

    if (getPlaceValue(last_steps, 2) != getPlaceValue(steps, 2)) {
        last_steps = setPlaceValue(last_steps, 2, getPlaceValue(steps, 2));
        lv_img_set_src(face_80_2_dial_3_85197, face_80_2_dial_2_85197_group[(steps / 10) % 10]);
    }

    if (getPlaceValue(last_steps, 3) != getPlaceValue(steps, 3)) {
        last_steps = setPlaceValue(last_steps, 3, getPlaceValue(steps, 3));
        lv_img_set_src(face_80_2_dial_4_85197, face_80_2_dial_2_85197_group[(steps / 100) % 10]);
    }

    if (getPlaceValue(last_steps, 4) != getPlaceValue(steps, 4)) {
        last_steps = setPlaceValue(last_steps, 4, getPlaceValue(steps, 4));
        lv_img_set_src(face_80_2_dial_5_85197, face_80_2_dial_2_85197_group[(steps / 1000) % 10]);
    }

    if (getPlaceValue(last_steps, 5) != getPlaceValue(steps, 5)) {
        last_steps = setPlaceValue(last_steps, 5, getPlaceValue(steps, 5));
        lv_img_set_src(face_80_2_dial_6_85197, face_80_2_dial_2_85197_group[(steps / 10000) % 10]);
    }

    if (getPlaceValue(last_kcal, 1) != getPlaceValue(kcal, 1)) {
        last_kcal = setPlaceValue(last_kcal, 1, getPlaceValue(kcal, 1));
        lv_img_set_src(face_80_2_dial_7_85197, face_80_2_dial_2_85197_group[(kcal / 1) % 10]);
    }

    if (getPlaceValue(last_kcal, 2) != getPlaceValue(kcal, 2)) {
        last_kcal = setPlaceValue(last_kcal, 2, getPlaceValue(kcal, 2));
        lv_img_set_src(face_80_2_dial_8_85197, face_80_2_dial_2_85197_group[(kcal / 10) % 10]);
    }

    if (getPlaceValue(last_kcal, 3) != getPlaceValue(kcal, 3)) {
        last_kcal = setPlaceValue(last_kcal, 3, getPlaceValue(kcal, 3));
        lv_img_set_src(face_80_2_dial_9_85197, face_80_2_dial_2_85197_group[(kcal / 100) % 10]);
    }

    if (getPlaceValue(last_kcal, 4) != getPlaceValue(kcal, 4)) {
        last_kcal = setPlaceValue(last_kcal, 4, getPlaceValue(kcal, 4));
        lv_img_set_src(face_80_2_dial_10_85197, face_80_2_dial_2_85197_group[(kcal / 1000) % 10]);
    }

    if (getPlaceValue(last_distance, 1) != getPlaceValue(distance, 1)) {
        last_distance = setPlaceValue(last_distance, 1, getPlaceValue(distance, 1));
        lv_img_set_src(face_80_2_dial_23_85197, face_80_2_dial_2_85197_group[(distance / 1) % 10]);
    }

    if (getPlaceValue(last_distance, 2) != getPlaceValue(distance, 2)) {
        last_distance = setPlaceValue(last_distance, 2, getPlaceValue(distance, 2));
        lv_img_set_src(face_80_2_dial_24_85197, face_80_2_dial_2_85197_group[(distance / 10) % 10]);
    }

    if (getPlaceValue(last_distance, 3) != getPlaceValue(distance, 3)) {
        last_distance = setPlaceValue(last_distance, 3, getPlaceValue(distance, 3));
        lv_img_set_src(face_80_2_dial_25_85197, face_80_2_dial_2_85197_group[(distance / 100) % 10]);
    }

}

static void watchface_80_2_dial_set_hrm(int32_t bpm, int32_t oxygen)
{
    if (!face_80_2_dial) {
        return;
    }

    lv_img_set_src(face_80_2_dial_27_85197, face_80_2_dial_2_85197_group[(bpm / 1) % 10]);
    lv_img_set_src(face_80_2_dial_28_85197, face_80_2_dial_2_85197_group[(bpm / 10) % 10]);
    lv_img_set_src(face_80_2_dial_29_85197, face_80_2_dial_2_85197_group[(bpm / 100) % 10]);

}

static void watchface_80_2_dial_set_weather(int8_t temp, int icon)
{
    if (!face_80_2_dial) {
        return;
    }

    lv_img_set_src(face_80_2_dial_53_86861, face_80_2_dial_43_86861_group[(temp / 1) % 10]);
    lv_img_set_src(face_80_2_dial_54_86861, face_80_2_dial_43_86861_group[(temp / 10) % 10]);
    if (temp >= 0) {
        lv_obj_add_flag(face_80_2_dial_56_25742, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_clear_flag(face_80_2_dial_56_25742, LV_OBJ_FLAG_HIDDEN);
    }
    lv_img_set_src(face_80_2_dial_58_84569, face_80_2_dial_weather[icon % 8]);

}

static void watchface_80_2_dial_set_ble_connected(bool connected)
{
    if (!face_80_2_dial) {
        return;
    }

}

static void watchface_80_2_dial_set_battery_percent(int32_t percent, int32_t battery)
{
    if (!face_80_2_dial) {
        return;
    }

}

static void watchface_80_2_dial_set_num_notifcations(int32_t number)
{
    if (!face_80_2_dial) {
        return;
    }

}

static void watchface_80_2_dial_set_watch_env_sensors(int temperature, int humidity, int pressure, float iaq, float co2)
{
    if (!face_80_2_dial) {
        return;
    }

}

void watchface_80_2_dial_show(watchface_app_evt_listener evt_cb, zsw_settings_watchface_t *settings)
{
    ui_80_2_dial_evt_cb = evt_cb;

    lv_obj_clear_flag(lv_scr_act(), LV_OBJ_FLAG_SCROLLABLE);
    face_80_2_dial = lv_obj_create(lv_scr_act());
    watchface_80_2_dial_invalidate_cached();

    lv_obj_clear_flag(face_80_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scrollbar_mode(face_80_2_dial, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_opa(face_80_2_dial, LV_OPA_TRANSP, LV_PART_MAIN);

    lv_obj_set_style_border_width(face_80_2_dial, 0, LV_PART_MAIN);
    lv_obj_set_size(face_80_2_dial, 240, 240);
    lv_obj_clear_flag(face_80_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_80_2_dial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_80_2_dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_80_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_80_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_80_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_80_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_80_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    face_80_2_dial_0_2768 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_0_2768, ZSW_LV_IMG_USE(face_80_2_dial_0_2768_0));
    lv_obj_set_width(face_80_2_dial_0_2768, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_0_2768, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_0_2768, 9);
    lv_obj_set_y(face_80_2_dial_0_2768, 71);
    lv_obj_add_flag(face_80_2_dial_0_2768, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_0_2768, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_1_24923 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_1_24923, ZSW_LV_IMG_USE(face_80_2_dial_1_24923_0));
    lv_obj_set_width(face_80_2_dial_1_24923, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_1_24923, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_1_24923, 123);
    lv_obj_set_y(face_80_2_dial_1_24923, 141);
    lv_obj_add_flag(face_80_2_dial_1_24923, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_1_24923, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_2_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_2_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_2_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_2_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_2_85197, 98);
    lv_obj_set_y(face_80_2_dial_2_85197, 108);
    lv_obj_add_flag(face_80_2_dial_2_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_2_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_3_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_3_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_3_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_3_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_3_85197, 85);
    lv_obj_set_y(face_80_2_dial_3_85197, 108);
    lv_obj_add_flag(face_80_2_dial_3_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_3_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_4_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_4_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_4_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_4_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_4_85197, 72);
    lv_obj_set_y(face_80_2_dial_4_85197, 108);
    lv_obj_add_flag(face_80_2_dial_4_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_4_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_5_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_5_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_5_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_5_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_5_85197, 59);
    lv_obj_set_y(face_80_2_dial_5_85197, 108);
    lv_obj_add_flag(face_80_2_dial_5_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_5_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_6_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_6_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_6_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_6_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_6_85197, 46);
    lv_obj_set_y(face_80_2_dial_6_85197, 108);
    lv_obj_add_flag(face_80_2_dial_6_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_6_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_7_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_7_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_7_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_7_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_7_85197, 175);
    lv_obj_set_y(face_80_2_dial_7_85197, 108);
    lv_obj_add_flag(face_80_2_dial_7_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_7_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_8_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_8_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_8_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_8_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_8_85197, 162);
    lv_obj_set_y(face_80_2_dial_8_85197, 108);
    lv_obj_add_flag(face_80_2_dial_8_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_8_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_9_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_9_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_9_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_9_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_9_85197, 149);
    lv_obj_set_y(face_80_2_dial_9_85197, 108);
    lv_obj_add_flag(face_80_2_dial_9_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_9_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_10_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_10_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_10_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_10_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_10_85197, 136);
    lv_obj_set_y(face_80_2_dial_10_85197, 108);
    lv_obj_add_flag(face_80_2_dial_10_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_10_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_12_94522 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_12_94522, ZSW_LV_IMG_USE(face_80_2_dial_12_94522_0));
    lv_obj_set_width(face_80_2_dial_12_94522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_12_94522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_12_94522, 26);
    lv_obj_set_y(face_80_2_dial_12_94522, 161);
    lv_obj_add_flag(face_80_2_dial_12_94522, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_12_94522, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_14_89131 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_14_89131, ZSW_LV_IMG_USE(face_80_2_dial_14_89131_0));
    lv_obj_set_width(face_80_2_dial_14_89131, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_14_89131, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_14_89131, 51);
    lv_obj_set_y(face_80_2_dial_14_89131, 179);
    lv_obj_add_flag(face_80_2_dial_14_89131, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_14_89131, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_16_89866 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_16_89866, ZSW_LV_IMG_USE(face_80_2_dial_16_89866_0));
    lv_obj_set_width(face_80_2_dial_16_89866, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_16_89866, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_16_89866, 87);
    lv_obj_set_y(face_80_2_dial_16_89866, 179);
    lv_obj_add_flag(face_80_2_dial_16_89866, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_16_89866, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_17_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_17_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_17_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_17_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_17_85197, 39);
    lv_obj_set_y(face_80_2_dial_17_85197, 178);
    lv_obj_add_flag(face_80_2_dial_17_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_17_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_18_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_18_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_18_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_18_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_18_85197, 27);
    lv_obj_set_y(face_80_2_dial_18_85197, 178);
    lv_obj_add_flag(face_80_2_dial_18_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_18_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_19_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_19_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_19_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_19_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_19_85197, 75);
    lv_obj_set_y(face_80_2_dial_19_85197, 178);
    lv_obj_add_flag(face_80_2_dial_19_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_19_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_20_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_20_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_20_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_20_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_20_85197, 63);
    lv_obj_set_y(face_80_2_dial_20_85197, 178);
    lv_obj_add_flag(face_80_2_dial_20_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_20_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_21_89292 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_21_89292, ZSW_LV_IMG_USE(face_80_2_dial_21_89292_0));
    lv_obj_set_width(face_80_2_dial_21_89292, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_21_89292, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_21_89292, 58);
    lv_obj_set_y(face_80_2_dial_21_89292, 197);
    lv_obj_add_flag(face_80_2_dial_21_89292, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_21_89292, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_22_89272 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_22_89272, ZSW_LV_IMG_USE(face_80_2_dial_22_89272_0));
    lv_obj_set_width(face_80_2_dial_22_89272, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_22_89272, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_22_89272, 91);
    lv_obj_set_y(face_80_2_dial_22_89272, 211);
    lv_obj_add_flag(face_80_2_dial_22_89272, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_22_89272, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_23_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_23_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_23_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_23_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_23_85197, 108);
    lv_obj_set_y(face_80_2_dial_23_85197, 197);
    lv_obj_add_flag(face_80_2_dial_23_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_23_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_24_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_24_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_24_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_24_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_24_85197, 96);
    lv_obj_set_y(face_80_2_dial_24_85197, 197);
    lv_obj_add_flag(face_80_2_dial_24_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_24_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_25_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_25_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_25_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_25_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_25_85197, 78);
    lv_obj_set_y(face_80_2_dial_25_85197, 197);
    lv_obj_add_flag(face_80_2_dial_25_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_25_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_26_88651 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_26_88651, ZSW_LV_IMG_USE(face_80_2_dial_26_88651_0));
    lv_obj_set_width(face_80_2_dial_26_88651, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_26_88651, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_26_88651, 85);
    lv_obj_set_y(face_80_2_dial_26_88651, 218);
    lv_obj_add_flag(face_80_2_dial_26_88651, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_26_88651, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_27_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_27_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_27_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_27_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_27_85197, 131);
    lv_obj_set_y(face_80_2_dial_27_85197, 217);
    lv_obj_add_flag(face_80_2_dial_27_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_27_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_28_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_28_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_28_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_28_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_28_85197, 119);
    lv_obj_set_y(face_80_2_dial_28_85197, 217);
    lv_obj_add_flag(face_80_2_dial_28_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_28_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_29_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_29_85197, ZSW_LV_IMG_USE(face_80_2_dial_2_85197_0));
    lv_obj_set_width(face_80_2_dial_29_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_29_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_29_85197, 107);
    lv_obj_set_y(face_80_2_dial_29_85197, 217);
    lv_obj_add_flag(face_80_2_dial_29_85197, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_29_85197, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_31_2056 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_31_2056, ZSW_LV_IMG_USE(face_80_2_dial_31_2056_0));
    lv_obj_set_width(face_80_2_dial_31_2056, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_31_2056, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_31_2056, 44);
    lv_obj_set_y(face_80_2_dial_31_2056, 141);
    lv_obj_add_flag(face_80_2_dial_31_2056, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_31_2056, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_33_92190 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_33_92190, ZSW_LV_IMG_USE(face_80_2_dial_33_92190_0));
    lv_obj_set_width(face_80_2_dial_33_92190, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_33_92190, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_33_92190, 77);
    lv_obj_set_y(face_80_2_dial_33_92190, 141);
    lv_obj_add_flag(face_80_2_dial_33_92190, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_33_92190, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_35_113802 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_35_113802, ZSW_LV_IMG_USE(face_80_2_dial_35_113802_0));
    lv_obj_set_width(face_80_2_dial_35_113802, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_35_113802, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_35_113802, 98);
    lv_obj_set_y(face_80_2_dial_35_113802, 8);
    lv_obj_add_flag(face_80_2_dial_35_113802, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_35_113802, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_36_96224 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_36_96224, ZSW_LV_IMG_USE(face_80_2_dial_36_96224_0));
    lv_obj_set_width(face_80_2_dial_36_96224, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_36_96224, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_36_96224, 117);
    lv_obj_set_y(face_80_2_dial_36_96224, 39);
    lv_obj_add_flag(face_80_2_dial_36_96224, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_36_96224, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_37_96394 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_37_96394, ZSW_LV_IMG_USE(face_80_2_dial_37_96394_0));
    lv_obj_set_width(face_80_2_dial_37_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_37_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_37_96394, 79);
    lv_obj_set_y(face_80_2_dial_37_96394, 29);
    lv_obj_add_flag(face_80_2_dial_37_96394, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_37_96394, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_38_96394 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_38_96394, ZSW_LV_IMG_USE(face_80_2_dial_37_96394_0));
    lv_obj_set_width(face_80_2_dial_38_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_38_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_38_96394, 50);
    lv_obj_set_y(face_80_2_dial_38_96394, 29);
    lv_obj_add_flag(face_80_2_dial_38_96394, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_38_96394, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_39_96394 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_39_96394, ZSW_LV_IMG_USE(face_80_2_dial_37_96394_0));
    lv_obj_set_width(face_80_2_dial_39_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_39_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_39_96394, 166);
    lv_obj_set_y(face_80_2_dial_39_96394, 29);
    lv_obj_add_flag(face_80_2_dial_39_96394, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_39_96394, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_40_96394 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_40_96394, ZSW_LV_IMG_USE(face_80_2_dial_37_96394_0));
    lv_obj_set_width(face_80_2_dial_40_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_40_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_40_96394, 137);
    lv_obj_set_y(face_80_2_dial_40_96394, 29);
    lv_obj_add_flag(face_80_2_dial_40_96394, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_40_96394, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_41_86829 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_41_86829, ZSW_LV_IMG_USE(face_80_2_dial_41_86829_0));
    lv_obj_set_width(face_80_2_dial_41_86829, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_41_86829, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_41_86829, 172);
    lv_obj_set_y(face_80_2_dial_41_86829, 85);
    lv_obj_add_flag(face_80_2_dial_41_86829, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_41_86829, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_42_86829 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_42_86829, ZSW_LV_IMG_USE(face_80_2_dial_41_86829_0));
    lv_obj_set_width(face_80_2_dial_42_86829, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_42_86829, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_42_86829, 139);
    lv_obj_set_y(face_80_2_dial_42_86829, 85);
    lv_obj_add_flag(face_80_2_dial_42_86829, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_42_86829, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_43_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_43_86861, ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0));
    lv_obj_set_width(face_80_2_dial_43_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_43_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_43_86861, 127);
    lv_obj_set_y(face_80_2_dial_43_86861, 80);
    lv_obj_add_flag(face_80_2_dial_43_86861, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_43_86861, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_44_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_44_86861, ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0));
    lv_obj_set_width(face_80_2_dial_44_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_44_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_44_86861, 115);
    lv_obj_set_y(face_80_2_dial_44_86861, 80);
    lv_obj_add_flag(face_80_2_dial_44_86861, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_44_86861, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_45_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_45_86861, ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0));
    lv_obj_set_width(face_80_2_dial_45_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_45_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_45_86861, 103);
    lv_obj_set_y(face_80_2_dial_45_86861, 80);
    lv_obj_add_flag(face_80_2_dial_45_86861, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_45_86861, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_46_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_46_86861, ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0));
    lv_obj_set_width(face_80_2_dial_46_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_46_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_46_86861, 91);
    lv_obj_set_y(face_80_2_dial_46_86861, 80);
    lv_obj_add_flag(face_80_2_dial_46_86861, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_46_86861, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_47_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_47_86861, ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0));
    lv_obj_set_width(face_80_2_dial_47_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_47_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_47_86861, 160);
    lv_obj_set_y(face_80_2_dial_47_86861, 80);
    lv_obj_add_flag(face_80_2_dial_47_86861, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_47_86861, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_48_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_48_86861, ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0));
    lv_obj_set_width(face_80_2_dial_48_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_48_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_48_86861, 148);
    lv_obj_set_y(face_80_2_dial_48_86861, 80);
    lv_obj_add_flag(face_80_2_dial_48_86861, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_48_86861, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_49_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_49_86861, ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0));
    lv_obj_set_width(face_80_2_dial_49_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_49_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_49_86861, 193);
    lv_obj_set_y(face_80_2_dial_49_86861, 80);
    lv_obj_add_flag(face_80_2_dial_49_86861, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_49_86861, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_50_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_50_86861, ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0));
    lv_obj_set_width(face_80_2_dial_50_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_50_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_50_86861, 181);
    lv_obj_set_y(face_80_2_dial_50_86861, 80);
    lv_obj_add_flag(face_80_2_dial_50_86861, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_50_86861, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_53_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_53_86861, ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0));
    lv_obj_set_width(face_80_2_dial_53_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_53_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_53_86861, 60);
    lv_obj_set_y(face_80_2_dial_53_86861, 80);
    lv_obj_add_flag(face_80_2_dial_53_86861, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_53_86861, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_54_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_54_86861, ZSW_LV_IMG_USE(face_80_2_dial_43_86861_0));
    lv_obj_set_width(face_80_2_dial_54_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_54_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_54_86861, 48);
    lv_obj_set_y(face_80_2_dial_54_86861, 80);
    lv_obj_add_flag(face_80_2_dial_54_86861, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_54_86861, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_55_106772 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_55_106772, ZSW_LV_IMG_USE(face_80_2_dial_55_106772_0));
    lv_obj_set_width(face_80_2_dial_55_106772, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_55_106772, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_55_106772, 72);
    lv_obj_set_y(face_80_2_dial_55_106772, 80);
    lv_obj_add_flag(face_80_2_dial_55_106772, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_55_106772, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_56_25742 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_56_25742, ZSW_LV_IMG_USE(face_80_2_dial_51_25742_0));
    lv_obj_set_width(face_80_2_dial_56_25742, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_56_25742, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_56_25742, 42);
    lv_obj_set_y(face_80_2_dial_56_25742, 74);
    lv_obj_add_flag(face_80_2_dial_56_25742, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_56_25742, LV_OBJ_FLAG_SCROLLABLE);

    face_80_2_dial_58_84569 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_58_84569, ZSW_LV_IMG_USE(face_80_2_dial_58_84569_0));
    lv_obj_set_width(face_80_2_dial_58_84569, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_58_84569, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_58_84569, 20);
    lv_obj_set_y(face_80_2_dial_58_84569, 61);
    lv_obj_add_flag(face_80_2_dial_58_84569, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_80_2_dial_58_84569, LV_OBJ_FLAG_SCROLLABLE);

}

static watchface_ui_api_t ui_api = {
    .show = watchface_80_2_dial_show,
    .remove = watchface_80_2_dial_remove,
    .set_battery_percent = watchface_80_2_dial_set_battery_percent,
    .set_hrm = watchface_80_2_dial_set_hrm,
    .set_step = watchface_80_2_dial_set_step,
    .set_ble_connected = watchface_80_2_dial_set_ble_connected,
    .set_num_notifcations = watchface_80_2_dial_set_num_notifcations,
    .set_weather = watchface_80_2_dial_set_weather,
    .set_datetime = watchface_80_2_dial_set_datetime,
    .set_watch_env_sensors = watchface_80_2_dial_set_watch_env_sensors,
    .ui_invalidate_cached = watchface_80_2_dial_invalidate_cached,
    .get_preview_img = watchface_80_2_dial_get_preview_img,
};

static int watchface_80_2_dial_init(void)
{
    watchface_app_register_ui(&ui_api);

    return 0;
}

SYS_INIT(watchface_80_2_dial_init, APPLICATION, WATCHFACE_UI_INIT_PRIO);
