# Copyright (c) 2026 ZSWatch Project
# SPDX-License-Identifier: Apache-2.0

CONFIG_ZSW_TEST_SKIP_ONBOARDING=y

CONFIG_ASSERT_VERBOSE=y

# Enable info-level logs for key modules during testing
CONFIG_ZSW_UI_CONTROLLER_LOG_LEVEL_INF=y
CONFIG_ZSW_APP_LOG_LEVEL_INF=y
