
// File generated by bin2lvgl
// developed by fbiego.
// https://github.com/fbiego
// modified by Daniel Kampert.
// https://github.com/kampi
// Watchface: 75_2_dial

#include <lvgl.h>

#include <zephyr/logging/log.h>

#include "ui/zsw_ui.h"
#include "applications/watchface/watchface_app.h"
#include "ui/watchfaces/zsw_ui_notification_area.h"

LOG_MODULE_REGISTER(watchface_75_2_dial, LOG_LEVEL_WRN);

static lv_obj_t *face_75_2_dial;
static lv_obj_t *face_75_2_dial = NULL;
static watchface_app_evt_listener ui_75_2_dial_evt_cb;
static zsw_ui_notification_area_t *zsw_ui_notifications_area;

static int last_date = -1;
static int last_day = -1;
static int last_month = -1;
static int last_year = -1;
static int last_weekday = -1;
static int last_hour = -1;
static int last_minute = -1;

static int last_steps = -1;
static int last_distance = -1;
static int last_kcal = -1;

static lv_obj_t *face_75_2_dial_0_1024;
static lv_obj_t *face_75_2_dial_2_216824;
static lv_obj_t *face_75_2_dial_3_59132;
static lv_obj_t *face_75_2_dial_19_89191;
static lv_obj_t *face_75_2_dial_35_138999;

ZSW_LV_IMG_DECLARE(face_75_2_dial_0_1024_0);
ZSW_LV_IMG_DECLARE(face_75_2_dial_1_213131_0);
ZSW_LV_IMG_DECLARE(face_75_2_dial_1_213131_1);
ZSW_LV_IMG_DECLARE(face_75_2_dial_1_213131_2);
ZSW_LV_IMG_DECLARE(face_75_2_dial_1_213131_3);
ZSW_LV_IMG_DECLARE(face_75_2_dial_1_213131_4);
ZSW_LV_IMG_DECLARE(face_75_2_dial_1_213131_5);
ZSW_LV_IMG_DECLARE(face_75_2_dial_1_213131_6);
ZSW_LV_IMG_DECLARE(face_75_2_dial_2_216824_0);
ZSW_LV_IMG_DECLARE(face_75_2_dial_2_216824_1);
ZSW_LV_IMG_DECLARE(face_75_2_dial_2_216824_2);
ZSW_LV_IMG_DECLARE(face_75_2_dial_2_216824_3);
ZSW_LV_IMG_DECLARE(face_75_2_dial_2_216824_4);
ZSW_LV_IMG_DECLARE(face_75_2_dial_2_216824_5);
ZSW_LV_IMG_DECLARE(face_75_2_dial_2_216824_6);
LV_IMG_DECLARE(face_75_2_dial_3_59132_0);
LV_IMG_DECLARE(face_75_2_dial_19_89191_0);
LV_IMG_DECLARE(face_75_2_dial_35_138999_0);
ZSW_LV_IMG_DECLARE(face_75_2_dial_preview_0);

#if CONFIG_LV_COLOR_DEPTH_16 != 1
#error "CONFIG_LV_COLOR_DEPTH_16 should be 16 bit for watchfaces"
#endif
#if CONFIG_LV_COLOR_16_SWAP != 1
#error "CONFIG_LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif

const void *face_75_2_dial_1_213131_group[] = {
    ZSW_LV_IMG_USE(face_75_2_dial_1_213131_0),
    ZSW_LV_IMG_USE(face_75_2_dial_1_213131_1),
    ZSW_LV_IMG_USE(face_75_2_dial_1_213131_2),
    ZSW_LV_IMG_USE(face_75_2_dial_1_213131_3),
    ZSW_LV_IMG_USE(face_75_2_dial_1_213131_4),
    ZSW_LV_IMG_USE(face_75_2_dial_1_213131_5),
    ZSW_LV_IMG_USE(face_75_2_dial_1_213131_6),
};
const void *face_75_2_dial_2_216824_group[] = {
    ZSW_LV_IMG_USE(face_75_2_dial_2_216824_0),
    ZSW_LV_IMG_USE(face_75_2_dial_2_216824_1),
    ZSW_LV_IMG_USE(face_75_2_dial_2_216824_2),
    ZSW_LV_IMG_USE(face_75_2_dial_2_216824_3),
    ZSW_LV_IMG_USE(face_75_2_dial_2_216824_4),
    ZSW_LV_IMG_USE(face_75_2_dial_2_216824_5),
    ZSW_LV_IMG_USE(face_75_2_dial_2_216824_6),
};

static int32_t getPlaceValue(int32_t num, int32_t place)
{
    int32_t divisor = 1;
    for (uint32_t i = 1; i < place; i++) {
        divisor *= 10;
    }
    return (num / divisor) % 10;
}

static int32_t setPlaceValue(int32_t num, int32_t place, int32_t newValue)
{
    int32_t divisor = 1;
    for (uint32_t i = 1; i < place; i++) {
        divisor *= 10;
    }
    return num - ((num / divisor) % 10 * divisor) + (newValue * divisor);
}

static void watchface_75_2_dial_remove(void)
{
    if (!face_75_2_dial) {
        return;
    }

    lv_obj_del(face_75_2_dial);
    face_75_2_dial = NULL;
}

static void watchface_75_2_dial_invalidate_cached(void)
{
    last_date = -1;
    last_day = -1;
    last_month = -1;
    last_year = -1;
    last_weekday = -1;
    last_hour = -1;
    last_minute = -1;
    last_steps = -1;
    last_distance = -1;
    last_kcal = -1;
}

static const void *watchface_75_2_dial_get_preview_img(void)
{
    return ZSW_LV_IMG_USE(face_75_2_dial_preview_0);
}

static void watchface_75_2_dial_set_datetime(int day_of_week, int date, int day, int month, int year, int weekday,
                                             int hour,
                                             int minute, int second, uint32_t usec, bool am, bool mode)
{
    if (!face_75_2_dial) {
        return;
    }

    if (getPlaceValue(last_weekday, 1) != getPlaceValue(weekday, 1)) {
        last_weekday = setPlaceValue(last_weekday, 1, getPlaceValue(weekday, 1));
        lv_img_set_src(face_75_2_dial_2_216824, face_75_2_dial_2_216824_group[((weekday + 6) / 1) % 7]);
    }
    lv_img_set_angle(face_75_2_dial_3_59132, hour * 300 + (minute * 5));
    lv_img_set_angle(face_75_2_dial_19_89191, minute * 60);
    lv_img_set_angle(face_75_2_dial_35_138999, second * 60);

}

static void watchface_75_2_dial_set_step(int32_t steps, int32_t distance, int32_t kcal)
{
    if (!face_75_2_dial) {
        return;
    }

}

static void watchface_75_2_dial_set_hrm(int32_t bpm, int32_t oxygen)
{
    if (!face_75_2_dial) {
        return;
    }

}

static void watchface_75_2_dial_set_weather(int8_t temp, int icon)
{
    if (!face_75_2_dial) {
        return;
    }

}

static void watchface_75_2_dial_set_ble_connected(bool connected)
{
    if (!face_75_2_dial) {
        return;
    }

    zsw_ui_notification_area_ble_connected(zsw_ui_notifications_area, connected);
}

static void watchface_75_2_dial_set_battery_percent(int32_t percent, int32_t battery)
{
    if (!face_75_2_dial) {
        return;
    }

}

static void watchface_75_2_dial_set_num_notifcations(int32_t number)
{
    if (!face_75_2_dial) {
        return;
    }

    zsw_ui_notification_area_num_notifications(zsw_ui_notifications_area, number);
}

static void watchface_75_2_dial_set_watch_env_sensors(int temperature, int humidity, int pressure, float iaq, float co2)
{
    if (!face_75_2_dial) {
        return;
    }

}

void watchface_75_2_dial_show(watchface_app_evt_listener evt_cb, zsw_settings_watchface_t *settings)
{
    ui_75_2_dial_evt_cb = evt_cb;

    lv_obj_clear_flag(lv_scr_act(), LV_OBJ_FLAG_SCROLLABLE);
    face_75_2_dial = lv_obj_create(lv_scr_act());
    watchface_75_2_dial_invalidate_cached();

    lv_obj_clear_flag(face_75_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scrollbar_mode(face_75_2_dial, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_opa(face_75_2_dial, LV_OPA_TRANSP, LV_PART_MAIN);

    lv_obj_set_style_border_width(face_75_2_dial, 0, LV_PART_MAIN);
    lv_obj_set_size(face_75_2_dial, 240, 240);
    lv_obj_clear_flag(face_75_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_75_2_dial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_75_2_dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_75_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_75_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_75_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_75_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_75_2_dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    face_75_2_dial_0_1024 = lv_img_create(face_75_2_dial);
    lv_img_set_src(face_75_2_dial_0_1024, ZSW_LV_IMG_USE(face_75_2_dial_0_1024_0));
    lv_obj_set_width(face_75_2_dial_0_1024, LV_SIZE_CONTENT);
    lv_obj_set_height(face_75_2_dial_0_1024, LV_SIZE_CONTENT);
    lv_obj_set_x(face_75_2_dial_0_1024, 0);
    lv_obj_set_y(face_75_2_dial_0_1024, 0);
    lv_obj_add_flag(face_75_2_dial_0_1024, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_75_2_dial_0_1024, LV_OBJ_FLAG_SCROLLABLE);

    face_75_2_dial_2_216824 = lv_img_create(face_75_2_dial);
    lv_img_set_src(face_75_2_dial_2_216824, ZSW_LV_IMG_USE(face_75_2_dial_2_216824_0));
    lv_obj_set_width(face_75_2_dial_2_216824, LV_SIZE_CONTENT);
    lv_obj_set_height(face_75_2_dial_2_216824, LV_SIZE_CONTENT);
    lv_obj_set_x(face_75_2_dial_2_216824, 103);
    lv_obj_set_y(face_75_2_dial_2_216824, 68);
    lv_obj_add_flag(face_75_2_dial_2_216824, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_75_2_dial_2_216824, LV_OBJ_FLAG_SCROLLABLE);

    face_75_2_dial_3_59132 = lv_img_create(face_75_2_dial);
    lv_img_set_src(face_75_2_dial_3_59132, &face_75_2_dial_3_59132_0);
    lv_obj_set_width(face_75_2_dial_3_59132, LV_SIZE_CONTENT);
    lv_obj_set_height(face_75_2_dial_3_59132, LV_SIZE_CONTENT);
    lv_obj_set_x(face_75_2_dial_3_59132, 115);
    lv_obj_set_y(face_75_2_dial_3_59132, 59);
    lv_obj_add_flag(face_75_2_dial_3_59132, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_75_2_dial_3_59132, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(face_75_2_dial_3_59132, 5, 61);

    face_75_2_dial_19_89191 = lv_img_create(face_75_2_dial);
    lv_img_set_src(face_75_2_dial_19_89191, &face_75_2_dial_19_89191_0);
    lv_obj_set_width(face_75_2_dial_19_89191, LV_SIZE_CONTENT);
    lv_obj_set_height(face_75_2_dial_19_89191, LV_SIZE_CONTENT);
    lv_obj_set_x(face_75_2_dial_19_89191, 115);
    lv_obj_set_y(face_75_2_dial_19_89191, 36);
    lv_obj_add_flag(face_75_2_dial_19_89191, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_75_2_dial_19_89191, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(face_75_2_dial_19_89191, 5, 84);

    face_75_2_dial_35_138999 = lv_img_create(face_75_2_dial);
    lv_img_set_src(face_75_2_dial_35_138999, &face_75_2_dial_35_138999_0);
    lv_obj_set_width(face_75_2_dial_35_138999, LV_SIZE_CONTENT);
    lv_obj_set_height(face_75_2_dial_35_138999, LV_SIZE_CONTENT);
    lv_obj_set_x(face_75_2_dial_35_138999, 115);
    lv_obj_set_y(face_75_2_dial_35_138999, 12);
    lv_obj_add_flag(face_75_2_dial_35_138999, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(face_75_2_dial_35_138999, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(face_75_2_dial_35_138999, 5, 108);

    zsw_ui_notifications_area = zsw_ui_notification_area_add(face_75_2_dial);
    lv_obj_set_pos(zsw_ui_notifications_area->ui_notifications_container, 0, 70);
}

static watchface_ui_api_t ui_api = {
    .show = watchface_75_2_dial_show,
    .remove = watchface_75_2_dial_remove,
    .set_battery_percent = watchface_75_2_dial_set_battery_percent,
    .set_hrm = watchface_75_2_dial_set_hrm,
    .set_step = watchface_75_2_dial_set_step,
    .set_ble_connected = watchface_75_2_dial_set_ble_connected,
    .set_num_notifcations = watchface_75_2_dial_set_num_notifcations,
    .set_weather = watchface_75_2_dial_set_weather,
    .set_datetime = watchface_75_2_dial_set_datetime,
    .set_watch_env_sensors = watchface_75_2_dial_set_watch_env_sensors,
    .ui_invalidate_cached = watchface_75_2_dial_invalidate_cached,
    .get_preview_img = watchface_75_2_dial_get_preview_img,
};

static int watchface_75_2_dial_init(void)
{
    watchface_app_register_ui(&ui_api);

    return 0;
}

SYS_INIT(watchface_75_2_dial_init, APPLICATION, WATCHFACE_UI_INIT_PRIO);
