list(
  APPEND
  PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/app_picker/app_picker_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/music_app/music_app_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/lvgl_editor_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/lvgl_editor.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/montserrat_14_full_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/montserrat_10_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/montserrat_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/montserrat_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_play_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_pause_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_skip_forward_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_skip_back_data.c)